### ISSUE TITLE
Thumbnails on search results

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#1]
One of four thumbnails should appear in the search results for records in Open Vault:

Unique thumbnail - includes all records for digitized video, some records for digitized audio, and records for images
Digitized Audio Icon Thumbnail - records for digitized audio that do not have a unique thumbnail
Non-Digitized Audio Thumbnail - records for non-digitized audio
Non-Digitized Video Thumbnail - records for non-digitized video

**Comment by mccalluc** [comment]
@caseyedavis12 : will someone be providing the icons?

**Comment by Muraszko** [comment]
@mccalluc They are provided [here] (https://wgbh365-my.sharepoint.com/personal/michael_muraszko_wgbh_org/_layouts/15/guestaccess.aspx?guestaccesstoken=d2WP3VYrolkAfZ3yvHvAfVRAGHjMkN5JBg%2bnO%2b8LF6M%3d&docid=2_12ec2364298cc42938cd04028c14877cb) and in an email I sent you last week with the subject, "OpenVault Redesign deliverables"

**Comment by mccalluc** [comment]
I think this is complete.
