### ISSUE TITLE
Special Collections

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#10]
On the homepage, a box appears below the rotating gallery that says "Special Collections." See: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553422/OpenVault_final%20comps_v3.jpg

When a user clicks on this button, it takes the user to the special collections index page. The special collections are ordered from most popular to least popular (order coming soon): https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553428/OpenVault_final%20comps_v36.jpg

When a user clicks on one of the special collections, the user is taken to that special collection with the left-most tab as default: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553429/OpenVault_final%20comps_v37.jpg

**Comment by Muraszko** [comment]
email with text and images sent 12/24/2015

**Comment by mccalluc** [comment]
All of this is in place. (Ordering of collections has its own bug.)
