### ISSUE TITLE
S3 403s during ingest?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#106]
Do these reproduce? Is the media missing?

>
WARN [2016-01-29 15:21:37]: 1 (0.0%) PBCoreIngester::ValidationError: Method validation errors: HEAD https://s3.amazonaws.com/openvault.wgbh.org/catalog/asset_proxies/V_5DAAFC32ACEA4309B587D8F44678C090.webm (from #proxy_srcs) not 200: 403 Forbidden
>
WARN [2016-01-29 15:21:37]: 1 (0.0%) PBCoreIngester::ValidationError: Method validation errors: HEAD https://s3.amazonaws.com/openvault.wgbh.org/catalog/asset_proxies/V_96E3AD934B874D208D703C4C164E1B96.webm (from #proxy_srcs) not 200: 403 Forbidden

**Comment by Muraszko** [comment]
@mccalluc 
I had the file extensions incorrectly named .mp4.webm.
I've removed the incorrectly named versions and replaced them both with the correct ones.  Sorry about that, good catch.
From the log:
```
2016-02-01 07:22:40  182837104 catalog/asset_proxies/V_96E3AD934B874D208D703C4C164E1B96.webm
2016-02-01 07:22:04  100305666 catalog/asset_proxies/V_5DAAFC32ACEA4309B587D8F44678C090.webm
```
