### ISSUE TITLE
So, having 200+ images on a collection page will not be pretty.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#107]
I should have pushed back on this earlier, but our collection pages can have hundreds of items, and the design calls for having a thumbnail for each of them. This is bad. Some options.
- Go back to a purely text-based listing.
- Paging: a lot of extra machinery, and it means ctrl-F won't work for users.
- Cataloging: Make finer grained categories, so each tab has a smaller number of items.
- Mix: Images for the first n, and then below the fold do text. <-- I'm leaning towards this.
- Lazy load: as you scroll down the page, load images. Not impossible, but this kind of stuff can be fragile, and you can always drag faster than the page can load.
- Status quo: not acceptable.

@caseyedavis12 / @Muraszko / @afred : need feedback.

**Comment by afred** [comment]
@mccalluc which collections are you referring to?

**Comment by caseyedavis12** [comment]
@mccalluc: I would opt to go with paging or lazy load. If paging, can we have options for users to see 10, 20, 50, and 100 results?

**Comment by mccalluc** [comment]
- Again, paging precludes the user from using ctrl-f on a page: This is an unacceptable loss of functionality.
- Lazy load is possible, but again, this will be significant custom work and the end result will be fragile.
- Letting the user see 100 images at a time is precisely the problem.

**Comment by afred** [comment]
@caseyedavis12 just talked with @mccalluc and how about this?..

1. Have a curated set of "featured" items per each collection. This would be specified in the markdown somewhere.
1. Have a "See all ### records" link to a search that facets both on the collection name, and the field that contains whether it's "original footage", "interview", or whatever.

**Comment by caseyedavis12** [comment]
@afred and @mccalluc: This plan works for me.

**Comment by afred** [comment]
@mccalluc and in addition to the above...

1. On a search results page currently faceted by collection, display some collection-specific narrative above the search results (similar to AAPB).
1. On a search results page currently faceted by collection, provide a link back to the collection page (with the default tab active).
1. On a search results page currently faceted by collection _and_ genre (i.e. "interview", "original footage", etc), provide a link back to the collection page, with the tab associated with the faceted genre made active.

This assumes that the tabs for collection pages are facetable, and that the facet is "genre".

**Comment by afred** [comment]
@caseyedavis12 Is it important to be able to facet on collection only? Or would it suffice to be able to facet on collection+tab?

For instance, the index is set up to do searches for "Vietnam Interviews", "Vietnam Photographs", "Vietnam Original Footage", and "Vietnam Archival Footage".

It's not currently set up for "Vietnam - All Items", i don't think it was part of the original spec. Is it important enough to add?

**Comment by caseyedavis12** [comment]
@afred: No, I don't think it is important enough to add. We can stick with showing all items within "sections" of each collection.

**Comment by afred** [comment]
@caseyedavis12 @mccalluc sweet, updated the comment above to reflect it.

**Comment by mccalluc** [comment]
Created a number of new bugs to capture all the work that needs to be done to make this happen; Nothing left here / closing.
