### ISSUE TITLE
Provide list of Special Collections ordering

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#11]
Casey and @murazsko will provide the ordering of the special collections from most popular to least popular.

**Comment by Muraszko** [comment]
Sent email 12/22/2015

**Comment by mccalluc** [comment]
@Muraszko : Are we trying to do this from server logs or analytics? Is anything blocking this?

**Comment by Muraszko** [comment]
A combination of analytics, order by which they were created and the amount of content within each. It's just waiting on Casey and I to finalize the order.

**Comment by caseyedavis12** [comment]
@Muraszko are you ok with this ordering that we discussed over email?

1) Vietnam
2) War and Peace
3) Say Brother
4) Rock and Roll
5) Advocates
6) March on Washington
7) From the WGBH Vault
8) New Television Workshop
9) Press and the People
10) Ten O'Clock News (link to Boston Local website)
11) American Archive of Public Broadcasting (link to AAPB Website)
12) WGBH Stock Sales (link to stock sales website).

**Comment by Muraszko** [comment]
@caseyedavis12 Looks good, thanks Casey!

**Comment by mccalluc** [comment]
Fixed in c208792
