### ISSUE TITLE
Make collection tab values end-user friendly?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#116]
Currently we are using moderately arcane strings like "vietnam_interview" to identify the items that belong in a particular collection tab. As long as this was internal, this was fine, but now it looks like collections will point to searches after all, and these strings will be visible in the search interface.

- Should the collection be separated from the tab, rather than being precomposed?
- and should they both be given end-user friendly strings?
- ... or do we special-case it so these particular facets when selected aren't shown in the UI?

@caseyedavis12  should decide how important this is, and then coordinate with @Muraszko to update the database, if necessary. I have assigned a tentative milestone. (Spawned from #107)

**Comment by caseyedavis12** [comment]
@mccalluc: I don't think it's a problem for it to retain the strings like vietnam_interview. We do the same on AAPB
![screen shot 2016-02-03 at 3 44 08 pm](https://cloud.githubusercontent.com/assets/5992135/12796502/16e32538-ca8d-11e5-876c-a8d91f680a7c.png)

**Comment by mccalluc** [comment]
I don't think the analogy works, but sure, if we don't need to worry about it, great.

**Comment by caseyedavis12** [comment]
@mccalluc if I am misunderstanding the issue, can we discuss in person tomorrow?
________________________________

**Comment by mccalluc** [comment]
We're not doing collection searches - This is unnecessary.
