### ISSUE TITLE
Curate featured items for each collection

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#119]
I would like to just choose the first 6 (?), but I'm guessing someone will feel like that the highlighted items for each collection need to be chosen by hand. This is more work, but whatever. (Spawned from #107)

**Comment by mccalluc** [comment]
@caseyedavis12 : please confirm that "curation" is necessary, and then assign back to me. To be clear, manual curation is more work for you, more complicated in the code (ie more work, and more likely to break), and I believe it's of negligible benefit. But your call.

**Comment by caseyedavis12** [comment]
@mccalluc: Could the items be populated randomly and show different thumbnails on each refresh/visit?

**Comment by mccalluc** [comment]
Yeah, that would be possible... though it's the sort of thing I might say is post-launch or discretionary. I don't think the whole site needs to be held up by this.

(And it's not a big thing, but it would really help to distinguish the stuff that really must happen so the site can go out as soon as possible.)

**Comment by caseyedavis12** [comment]
@mccalluc: It is my understanding that I would need to hand-select featured items, have a random selection of featured items, or we could have the first number of items in the collection section (alphabetically?) appear. If we cannot do the random selection, I would prefer to hand-select featured items. Should I select a multiple of 2? How about 10 featured items?

**Comment by caseyedavis12** [comment]
@mccalluc: I don't think that our primary goal is to have the site go out as soon as possible. The primary goal is to implement the MVP features we would like to have on the site and devote as much time as necessary (with a launch aimed for sometime in March, per Karen's recent approval).


I will go through the Launch features in Github and create priorities labels. We can review the priorities at our weekly meeting and monitor and adjust as we go -- still aiming for a March launch but understanding that the specific launch date is flexible within that month.


cc @afred @muraszko

**Comment by mccalluc** [comment]
@caseyedavis12 : please use https://github.com/WGBH/openvault3/milestones/pre-launch to highlight items you want done sooner than later, but if functionally every last bit of it is essential, then any finer gradations are a waste of time.

**Comment by mccalluc** [comment]
With it actually in place, I think it makes sense to keep the order and consider the text-only list below just an extension of what comes above. The grid above is big enough that it doesn't work like a gallery: If we scramble it, then there's a little bit of a mystery to the user about what the ordering is.

In any event, at the very least let's get feedback from design, and not continue the discussion here.
