### ISSUE TITLE
Remove results list injection from collections, add expansion of individual items, and link to all

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#120]
(Spawned from #107)

**Comment by mccalluc** [comment]
I would really, really like to keep a list of all the titles on the page. Imagine a user comes to the site wondering if "Casper Weinburger" had anything to say about nukes.

- (A) Through search:
  - click on "all items"
  - see the first 12
  - maybe try clicking "next" forever?
  - or maybe try adding a search, and failing, because both the first and last name are misspelled.
- (B) List on page:
  - visually scan sorted list, and there it is.
  - or, control-f "casp.." or "wein.." and the item is highlighted on the page.

Having all the links and names on the page is also better for seo, and will particularly help us in google searches for otherwise unconnected persons.

@caseyedavis12 : if we can take this direction, please confirm and assign back to me.

**Comment by caseyedavis12** [comment]
@mccalluc: Can we discuss in person?

**Comment by mccalluc** [comment]
same-ish page, but get it in early for design to review.

**Comment by mccalluc** [comment]
Decided to stick with injection.
