### ISSUE TITLE
Decide where /catalog route should go.

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#140]
**Done when** we decide where the `/catalog` route should go, and if it's a page we already have, go ahead and do it. If not, then make a new ticket for creating that page.

Currently `/catalog` goes here:
![image](https://cloud.githubusercontent.com/assets/1507490/12857996/5d1a0cf8-cc1b-11e5-8843-59998655b778.png)

**Comment by mccalluc** [comment]
@afred: This will be handled by #139: We'll redirect to add the missing "access" facet, and then we'll get that list. Keep this around until that is merged just to be sure.

**Comment by mccalluc** [comment]
Yep, just checked and it's working fine.
