### ISSUE TITLE
With only one year, we don't get the pretty UI?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#148]
Apply multiple facets and you can end up in a corner that looks like this:
<img width="580" alt="screen shot 2016-02-08 at 6 18 52 pm" src="https://cloud.githubusercontent.com/assets/730388/12902680/9e402826-ce90-11e5-9fa8-5f92225bd6b9.png">

**Comment by caseyedavis12** [comment]
@mccalluc: Why does the year drop-down menu appear far to the left of the Year facet?

**Comment by mccalluc** [comment]
@caseyedavis12 : The real problem is that it's not showing the slider, but yeah, there's a problem, and I know it needs to be fixed.

**Comment by mccalluc** [comment]
Here's what's going on:
blacklight_range_limit-5.1.0/lib/blacklight_range_limit/view_helper_override.rb:
```
      return "blacklight_range_limit/range_limit_panel" if range_config(display_facet.name) and should_show_limit(display_facet.name)
```
```
  def should_show_limit(solr_field)
    stats = stats_for_field(solr_field)
    
    (params["range"] && params["range"][solr_field]) ||
    (  stats &&
      stats["max"] > stats["min"]) ||
    ( !stats  && @response.total > 0 )
  end
```

which makes sense: if max = min, there's no "range", so you don't need a range selector.
