### ISSUE TITLE
Ingest OV data set on demo server

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#154]
**Done when** demo server has data that is searchable and at least one:
  1. one record with sparse metadata
  1. one with complete metadata
  1. one video
  1. one audio
  1. one with a transcript
  1. one photograph
  1. one that has not been digitized
  1. one that is in an exhibit or collection

**Comment by afred** [comment]
@mccalluc @caseyedavis12 ingest has finished, but not fully successful. Here is the [ingest summary](https://gist.github.com/afred/84dd137bae5b7704ae62), but it's confusing to me because:
  * I count 42,516 files in the data set, using `ls -1 2015_OV_MASTERS_FINAL_pbcoreRENAMED | wc -l`
  * the summary shows that a lot of errors occurred, but they only got logged as warnings. So it's not clear if these records got ingested anyway.
  * The totals and percentages in the summary do not appear to add up to the number of files in the dataset.

@mccalluc do you know what to make of that? Currently, I can't get a rails console open to inspect the index (see #214).

**Comment by mccalluc** [comment]
This has been done, and will be done again.
