### ISSUE TITLE
List of collection tags?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#165]
@Muraszko : If it's easy, could you paste the list of collection tab tags below? ie, all the things like "vietnam_interviews". It doesn't look like I actually need the higher-level collection tags ("vietnam").

(If this is tricky for some reason, I could write a script to grab it from the dump, but that would be a bit of work, (but not that hard.))

**Comment by Muraszko** [comment]
@mccalluc 
Here you go:
[open_vault_tag_lists.zip](https://github.com/WGBH/openvault3/files/125000/open_vault_tag_lists.zip)
I also included a txt file of just the collections, if you do end up needing it.
-Mike

**Comment by mccalluc** [comment]
@Muraszko, Say Brother on the current OV has these tabs:
-    Complete Collection
-    Civil Rights
-    Music Performances

The list you provided has:
- sb_clip
- sb_record

... which is fine with me, but wanted to point out the discrepancy.

**Comment by mccalluc** [comment]
and for NTW, was:
- Complete Collection
- Artists Showcase
- Frames of Reference

but I have:
- ntw_clip
- ntw_record

**Comment by Muraszko** [comment]
@mccalluc 
That's correct.  I didn't think using those same collection tab titles would be useful this time around because many of the current records in the tabs point to data only records with no media.  So I broke them both down into two, records with media clips and records that are records only.

**Comment by Muraszko** [comment]
If you need a title for the actual tags on those, maybe @caseyedavis12 can chime in?

**Comment by caseyedavis12** [comment]
@mccalluc @muraszko: I can't today but can tomorrow.



________________________________

**Comment by caseyedavis12** [comment]
@mccalluc: See attached recommendations

[OpenVault_Collection_Labels.csv.zip](https://github.com/WGBH/openvault3/files/125384/OpenVault_Collection_Labels.csv.zip)

**Comment by mccalluc** [comment]
@caseyedavis12 : thanks for the recommendations: For the moment I think we have tab names that work. One constraint is the amount of space we have to work with, so longer names are problematic. Maybe don't worry until you see the demo site up?

(If you do end up wanting to change these, just make the edits in the MD like always: the tab names = the "##" section headers.)
