### ISSUE TITLE
Could credits be another tab on each collection?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#17]
Right now they are stand-alone pages. Is that necessary? One concern might be simply the number of tabs: There's a finite amount of horizontal real-estate.

**Comment by caseyedavis12** [comment]
@mccalluc: I think credits could go under "Authors"

**Comment by mccalluc** [comment]
These are collections, not exhibits, so there are no authors, but in any event, you can put it wherever you think best. I've checked in the big, stand-alone credits pages under app/view/override/credits: You can copy the content out of there and paste it under a tab whenever you feel like it. Assigning to you.

**Comment by mccalluc** [comment]
When I last talked with Casey, the decision was that we didn't need any lengthy credits on the collection pages themselves: the site-wide pages were sufficient. Closing.
