### ISSUE TITLE
Try alternative view for date range facet

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#170]
**background:** #164 was merged in response to the default behavior of blacklight's date facet displaying oddly when there was only 1 date option.

However, showing the date range slider when their is only 1 date is also awkward.

**Done when** we take a stab at reverting to Blacklight's default behavior, but tweak the placement to make it look pretty.

**Comment by mccalluc** [comment]
One round-about approach to this would be tag-ex (#208): even after narrowing you would still see the full range of years.

**Comment by mccalluc** [comment]
@afred / @caseyedavis12 : what should happen with this? Options I can think of:
- Fine as is.
- use tag-ex to always show the full date-range of the collection.
- hide the graph if there is only 1 (or 2 or 3?) years covered.

**Comment by caseyedavis12** [comment]
@mccalluc: I think it is fine as is.

________________________________

**Comment by mccalluc** [comment]
ok. closing.
