### ISSUE TITLE
not digitized, but on AAPB?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#172]
V_120F2A8588A84D4D9F64358518FF7C50:
<img width="588" alt="screen shot 2016-02-11 at 10 26 42 am" src="https://cloud.githubusercontent.com/assets/730388/12980337/103c07cc-d0aa-11e5-9daf-3706f490962d.png">

This is what it will look like, when my fix for #8 is in. Do we want to message this differently? Obviously, it was been digitized, it's just not available here. Should it be playable here? Even if not, should it be faceted as digitized? Would we want to grab a still from AAPB if nothing else?

(Doing nothing is also a valid choice.)

**Comment by caseyedavis12** [comment]
@mccalluc: Sorry, I couldn't find this earlier.


Do we want to message this differently?


>>Instead, could the digitize-on-demand blurb say: This item has not been digitized. If you are interested in sponsoring the digitization of this title, Contact Us. In your message, please include the URL for this particular record.


>>COMMENT: Please make the text fill up the box.


Obviously, it was been digitized, it's just not available here. Should it be playable here?


>>Great IDEA!! We should 1) embed the video from AAPB's Sony Ci. 2) We should include a blurb below that video that says: "This video/audio was digitized by the American Archive of Public Broadcasting. To discover more content from public media stations across the country, visit [americanarchive.org](http://www.americanarchive.org)


Even if not, should it be faceted as digitized?

>>It should be faceted as digitized.


Would we want to grab a still from AAPB if nothing else?

>>Yes, please use the AAPB thumbnail already created for AAPB. This can be used on search results.

>>COMMENT: For all things that are truly not digitized, please use the icons created by Digital. They should be used on search results and on the record page where the player would go (like on AAP[&#X1f60e]

________________________________

**Comment by mccalluc** [comment]
(@caseyedavis12 : Just a markdown style point: prefixing with '>' means quotation, so the section above is inverted, and a little hard for someone outside to read. I'll fix...)

**Comment by mccalluc** [comment]
This could get complicated, but sub-tasks:
- This counts as digitized. Update pb_core.
- #178 for placeholder images.
- Related to that, I think we should keep the text the current width. Reasons given there.
- Play media from AAPB: This could get complicated, and would require loosening the referer check in the media_controller over in that project, and having special logic here to point over there. Won't be done any time soon.
- Wording changes. These seem arbitrary, and are longer than the text we have right now. I'm not going to do them right now, and with more eyes on it we can see if the current text is unclear.

**Comment by caseyedavis12** [comment]
@mccalluc: Can you show me a screenshot after you add the placeholder image? I think that the blank space on the text looks weird. If there is no transcript, I think it should fill up the box.

Regarding the wording changes, my primary purpose of changing it was to better communicate that it will cost the user money to digitize the tape. It may help filter the number of emails that @muraszko receives to only those who are actually willing to pay.

**Comment by afred** [comment]
@caseyedavis12 You can pre-populate the subject and body of `mailto` links. You don't want to go too crazy (because of escaping characters and what not), but you can stub out a basic message, that could include a link to the current item.

**Comment by afred** [comment]
@caseyedavis12 e.g. <a href="mailto:someone@example.com?Subject=Digitization%20request&body=Hello%2C%20I%20am%20interested%20in%20digitizing%20the%20following%20item%3A%0A%0Ahttp%3A%2F%2Famericanarchive.org%2Fcatalog%2Fcpb-aacip_204-4302vbmg" target="_top">Contact Us</a>

**Comment by afred** [comment]
if we pre-populate the email, could the text be reduced to this?

> This item has not been digitized. If you are interested in sponsoring digitization please, <a href="openvault@wgbh.org?Subject=Digitization%20request&body=Hello%2C%20I%20am%20interested%20in%20digitizing%20the%20following%20item%3A%0A%0Ahttp%3A%2F%2Famericanarchive.org%2Fcatalog%2Fcpb-aacip_204-4302vbmg" target="_top">Contact Us</a>.

**Comment by caseyedavis12** [comment]
@afred: Yes!

**Comment by mccalluc** [comment]
@Muraszko : Don't read this whole thread, but we have OV items that are not digitized, but can be viewed on AAPB. Could we just consider this a data problem? ie, copy the media files from the AAPB-Ci to the OV-S3, and update the FM records accordingly? I'd really like to avoid special purpose code for cross-site embedding.

**Comment by Muraszko** [comment]
@mccalluc It would be possible, but I'm not sure they want to have the video hosted in two places.  Plus, I'd have to process, add a watermark.  So it's up to Casey and how she wants to display or link out that information.

**Comment by caseyedavis12** [comment]
@mccalluc and I just decided that we will link out.


Casey will talk with @sroosa and @muraszko about how we will update Open Vault filemaker every time we add more WGBH content in the AAPB Online Reading Room.
