### ISSUE TITLE
Provide appropriately sized collection images

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#18]
I don't think we're confident on what that size should be, so don't jump into this. There are 3 different places they get used:
- home page
- collections index page
- individual collections

If we could use the same image on collection index and show, that'd be great. We might get pixelation if used on home page.

Also:
- Can we get a less washed out image for Rock and Roll?
- Can we get a photograph for Say Brother?

**Comment by caseyedavis12** [comment]
I emailed Jon Goldberg. He will be out of office until 1/5. I will let you know when I hear back, @mccalluc.

**Comment by Muraszko** [comment]
I've uploaded the first of these three sets of Special Collections images to S3.
Special Collection Top Images (414x238px) these are the images that will be displayed on the Special Collection individual pages.

https://s3.amazonaws.com/openvault.wgbh.org/special_collections_top_image/

**Comment by Muraszko** [comment]
Also worth noting, the Homepage images won't be for all the Special Collections (like it is on current OV).  So we can better pick and choose the images to use because they need to be 1200 x 558px so, like Chuck says, a low resolution image probably won't look great.

**Comment by Muraszko** [comment]
I've uploaded the Special Collections Index images to S3.
Special Collections Index images (545x327px) these are the images that will be displayed on the Special Collection index page.

https://s3.amazonaws.com/openvault.wgbh.org/special_collections_index/

**Comment by mccalluc** [comment]
And I've updated the MD to point at the s3 urls, and it looks good.
