### ISSUE TITLE
Avoid awkward wrapping of top-nav for narrow screens

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#181]
**We don't want this...**
![image](https://cloud.githubusercontent.com/assets/1507490/12987248/2a55801a-d0c9-11e5-8206-7387eab35be2.png)

**We do want this...**
![image](https://cloud.githubusercontent.com/assets/1507490/12987261/3f7efffc-d0c9-11e5-9357-f4189d2f90f0.png)

**Done when** top nav stacks instead of wraps for narrower screen widths. And if it's not too much trouble, aligning the stacked top nav to be flush with the logo on the left side would be nice too.

This may mean having the nav stack for all breakpoints below the widest one (or two).

**Comment by mccalluc** [comment]
(Not convinced these links should be there at all: see https://github.com/WGBH/openvault3/issues/180#issuecomment-184366747)
