### ISSUE TITLE
Discuss: transcript sync button? transcript search box?

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#186]
The transcript scrolling/synching looks fantastic @mccalluc! Very well done!

For the sake of making more work for us, I wanted to discuss two features that the old version of OV had for transcripts. These may be of limited use, and we may not want to implement them, but thought I'd bring them up.

There was a button that would re-sync the transcript to the current location of the media. This would be useful if the user has scrolled through the transcript independent of the media, thus deactivating the sync.

Also, the old version had a mini-search box for searching just the transcript. Not sure how useful this would be. There are a lot of jquery options out there for doing this, plus highlighting found terms, etc.

Style-wise, I was playing around and here's something I came up with. A menu for the transcript pages that tries not to get in the way...
![image](https://cloud.githubusercontent.com/assets/1507490/12990689/abbfaff8-d0d9-11e5-85f6-2b2b04f73cb5.png)

... and it's partially transparent...
![image](https://cloud.githubusercontent.com/assets/1507490/12990716/c8e5833c-d0d9-11e5-8e55-4fae15e146dc.png)

I realize this is a little bit of self-imposed scope creep, but it _is_ a feature that used to be there that isn't any longer.

Thoughts on the feature? Thoughts on the style idea?

**Comment by afred** [comment]
^ and i should add, I'm responsible for the feature not being there anymore, so I guess I feel like I should put it back in.

**Comment by mccalluc** [comment]
@afred?
> There was a button that would re-sync the transcript to the current location of the media.

So with the new one if you click on the player timeline or hit the play button it goes back into auto-scroll mode, or at least that was my intention. I think that satisfies the underlying need?
```javascript
        $player.on('play', function(){
            set_user_scroll(false);
        });
```

> Also, the old version had a mini-search box

Actually, the mockups had it, too: Ignored it and hoped no one would notice... I'm kind of reluctant to spend time doing something the browser already does perfectly well.

**Comment by afred** [comment]
@mccalluc To re-sync currently, you have to pause/play (if playing) or move to a different part of the video. A sync button would allow the user to move the transcript to the correct location without interrupting playback, which I don't think is currently possible.

I agree that Cmd+F works great, and I hate to be a broken record, but not very many people know how to use it effectively.

Another possibility would be to add a hint. I've seen this done before...
![image](https://cloud.githubusercontent.com/assets/1507490/12992266/4e4f6342-d0e1-11e5-8f24-b7048f63ed7f.png)

**Comment by afred** [comment]
... of course, adding a hint like that would require that you sniff the user agent.

**Comment by mccalluc** [comment]
- I'm ok with a "cmd + f" to search note.
- The part that's missing is an indication of the current section in the transcript... see if a background shade, or maybe a round-rect would help. (With that in place I think we decided that an explicit sync button isn't necessary, but we'll see.)
