### ISSUE TITLE
collection/exhibit swapped since OV2?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#19]
@caseyedavis12 : 
in OV2 it was
- scholar collections
- wgbh exhibits

in OV3 it will be
- scholar exhibits
- wgbh collections

If this is an accident, could we use the old system to reduce confusion in conversations going forward? Or if this is intentional, great: I just wanted to be sure it was an explicit choice.

**Comment by Muraszko** [comment]
![screen shot 2015-12-29 at 12 23 26 pm](https://cloud.githubusercontent.com/assets/6650285/12038535/fe9ec50e-ae26-11e5-9a78-b81fbb1129e8.jpg)
Scholar Exhibits
Special Collections
As far as I know from the mocks.

**Comment by caseyedavis12** [comment]
@muraszko @mccalluc: Yes, this is an intentional swap for OV3.

**Comment by mccalluc** [comment]
awesome. closing.
