### ISSUE TITLE
Thumbnails on Record Page

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#2]
One of four thumbnails should appear on the record pages in Open Vault:

Unique thumbnail - includes all records for digitized video, some records for digitized audio, and records for images
Digitized Audio Icon Thumbnail - records for digitized audio that do not have a unique thumbnail
Non-Digitized Audio Thumbnail - records for non-digitized audio
Non-Digitized Video Thumbnail - records for non-digitized video

**Comment by mccalluc** [comment]
(see  #1: not sure where the icons are coming from.)

**Comment by mccalluc** [comment]
I think this is in place.
