### ISSUE TITLE
Pick images for scholar exhibits

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#20]
The scholars exhibits index page needs images just like the collections. I'll put a placeholder in there, but someone who cares more should select images. (Probably wait until we've pinned down sizing.)

@caseyedavis12 : Are you a good person to pick images?

**Comment by Muraszko** [comment]
@mccalluc Scholar Exhibit images now available on S3
openvault.wgbh.org/scholar_exhibits/
```
tech-nostalgia
needlework
advocates
new_critical_television
boring_and_sachs
pan-african_liberation
boston_civil_rights
art_of_asian_cooking
nine_poets
eric_jackson
showing_status
julia_child
fenway_park
james_baldwin
leary_and_jobs
bibring
television_violence
zoom
```
Please ignore that three of the images are identical.

**Comment by mccalluc** [comment]
Filled in the slots.
