### ISSUE TITLE
Donations link not working

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#210]
We link to https://secure2.convio.net/... : That is a 404. Temporarily down, or is that no longer active?

(Link is from /about, and has badly encoded ampersands, but even when they are fixed it doesn't work for me?)

**Comment by caseyedavis12** [comment]
@mccalluc: We are in the process of setting up a new donations account with a different service (Kimbia). More soon.

**Comment by mccalluc** [comment]
Bad link is removed. For housekeeping, I'll close this, but feel free to file a new one if you need a reminder to self.
