### ISSUE TITLE
Ingest summary does not summarize warnings caused by non- "200 OK" status

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#211]
The ingester does a check on external URLs to make sure they are valid. For any that don't return a "200 OK", it issues a warning, but they don't get summarized, and cause the summary output to be less readable. [See this example](https://gist.github.com/afred/93f27752b7f05f691d4f).

**Done when:** non-200 warnings are grouped by the actual HTTP status returned and the method that that provides the URL. For example...
```
3 (3.0%) PBCoreIngester::ValidationError: Method validation errors: HEAD (from #outside_url) not 200: 302 Found
4 (4.0%) PBCoreIngester::ValidationError: Method validation errors: HEAD (from #outside_url) not 200: 500 Internal server error
5 (5.0%) PBCoreIngester::ValidationError: Method validation errors: HEAD (from #thumbnail_src) not 200: 302 Found
```

**NOTE:** This may be achievable simply by removing the offending URL from the error msg.

**Comment by mccalluc** [comment]
See PR. As for what caused these errors in the first place, I'm not sure. Right now, on the command line, I get 200s:
```
$ curl -I http://americanarchive.org/catalog/cpb-aacip_15-000006mf
HTTP/1.1 200 OK
