### ISSUE TITLE
Redundant titles for The Advocates

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#215]
/catalog/V_406305F1D1F04ED89BA1758165B12728:

>
Advocates; Should Congress Deregulate Trucking?; Should Congress Deregulate Trucking?

@Muraszko : does this matter? If so, can it be fixed in the database, or does it need to be handled downstream?

**Comment by Muraszko** [comment]
@mccalluc The Open Vault Title is just "Should Congress Deregulate Trucking?"  I think that's the only one to be displayed on the record page as the title.

**Comment by mccalluc** [comment]
(The DB will be edited to remove redundancy.)

**Comment by Muraszko** [comment]
Addressing this in #46 so closing.
