### ISSUE TITLE
Decide on what "title" should be used on collection pages

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#216]
@Muraszko : We don't know what string to use as the "title" of an item on the collection pages. Because very often they are coming from the same series, it doesn't seem that the series or program title always needs to be included. (For instance, on Vietnam or WPNA the particular program a clip was used in probably isn't that important, at least on a summary page?)

But there are exceptions:
- The New Television workshop collection actually has several different series represented, and for them we probably do want to include the program.
- Similarly, with Say Brother, the program name might help to give some context to the asset name?

Right now we have some code that removes common prefixes across a collection: it works, but it adds a lot of complexity, and if there is a simpler way of deciding on a title, that would be good.

(On the old site, these strings were hard coded.) Here are examples from the collection pages, and some possibilities for how they could be represented.

- Vietnam: A Television History; Roots of a War; Interview with Abbott Low Moffat, 1982
  - Interview with Abbott Low Moffat, 1982
- American Experience; Nixon; ARVN advance
  - ARVN advance
- War and Peace in the Nuclear Age; Carter's New World; Interview with A. I. (Aleksandr Ivanovich) Alekseev, 1986
  - Interview with A. I. (Aleksandr Ivanovich) Alekseev, 1986
- Say Brother; A.L.D. Focus; Aggrey Mbere on life under Apartheid
  - Aggrey Mbere on life under Apartheid
- Say Brother; Black Colleges National; Interview with Tom Satch Sanders
  - Interview with Tom Satch Sanders
- March on Washington for Jobs and Freedom; Civil Rights March on Washington, D.C. [Leaders marching from the Washington Monument to the Lincoln Memorial], 08/28/1963
  - Civil Rights March on Washington, D.C. [Leaders marching from the Washington Monument to the Lincoln Memorial], 08/28/1963

**Comment by Muraszko** [comment]
@mccalluc 
I think for the most part using <pbcoreTitle titleType="Open Vault Title"> on the Collection pages should be the titles to display, except for the Say Brother and other ones like you mention where additional program titles may be helpful.

Rather than make it more complex in code, I could just modify the Open Vault Title for any records that @caseyedavis12 feels should get that additional program information?

Or do you think that will mess up how your displaying the search results titles?

**Comment by mccalluc** [comment]
Talked: We'll just use the finest grained title, and New Television Workshop with be broken into more tabs.

**Comment by mccalluc** [comment]
Code has been changed to use `short_title`; #260 is filed to make new tags in the DB. Closing this.
