### ISSUE TITLE
Figure out "invalid byte sequence" errors during ingest

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#219]
https://gist.github.com/afred/93f27752b7f05f691d4f
```
WARN [2016-02-15 21:40:51]: 42516 (50.0%) ArgumentError: invalid byte sequence in UTF-8
```

**Comment by mccalluc** [comment]
```
$ ls -a ../../data/2015_OV_MASTERS_FINAL_pbcoreRENAMED | head
.
..
._A_00001AE5972C40FA83F0010A300EF965.xml
A_00001AE5972C40FA83F0010A300EF965.xml
._A_0002EAE07B21486E92779A2D01F9EC72.xml
A_0002EAE07B21486E92779A2D01F9EC72.xml
._A_00037F51FB8440A19B1DBAF663D688C5.xml
A_00037F51FB8440A19B1DBAF663D688C5.xml
._A_00087072368B4F9CA8E77EBDA8FCEF2C.xml
A_00087072368B4F9CA8E77EBDA8FCEF2C.xml
```
... and those `._A*` files are binary. No idea where they came from. @afred: If you want to clean them up, but hopefully we'll get a new export soon, in which it'll be easier just not to unzip the zip, since it can be read directly.

**Comment by afred** [comment]
D'oh! Thanks @mccalluc, I should have found that. Pretty sure the files beginning with `.` are an artifact of either of compression that I used: `tar -czvvf` to compress; and `tar -xzvvf` to uncompress.

**Comment by mccalluc** [comment]
@afred: FWIW: they've got "com.apple" in them... looks like some per file metadata that the mac keeps track of, but which shouldn't show up as an actual file.... resource fork/data fork stuff? It doesn't matter.
