### ISSUE TITLE
Home page text below each of the three buttons

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#22]

**Comment by caseyedavis12** [comment]
@mccalluc

WGBH Series: Browse titles in the WGBH Media Library and Archives collection.
Scholar Exhibits: Explore selected topics and digitized programs of historical significance curated by WGBH Mellon Scholars.
Special Collections: Check out collections of significant WGBH productions, including unique full-length interviews.

**Comment by mccalluc** [comment]
Filled it in with 094e180.
