### ISSUE TITLE
Scholar titles are much longer than ours -> what should change?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#23]
Titles on the scholar exhibits are much longer than on our collections, and we also want a by-line underneath. Not sure about the best way forward.
- Give all the scholar exhibits much taller yellow boxes.
- Skip the by lines on the index page. (In addition to shortening titles.)
- Truncate after x characters.
- Different UI.
- **Come up with shorter titles.** (Chuck's favorite)

The mockups have the titles in all-caps, which isn't a bad decision, but it really does not work well at all when the titles are more than a word or two.

**Comment by caseyedavis12** [comment]
@mccalluc: In the wireframes, it looks like the Scholar Exhibit Titles on the Exhibit Index page use a smaller font. 

Scholar Exhibits should not be all caps and should use the smaller font. 
WGBH Collections should be all caps and use the larger font. I do not see font size specified anywhere. Do you?

**Comment by mccalluc** [comment]
I'm using a smaller font, with a larger box, and it seems like enough for now.
