### ISSUE TITLE
Align audio player with img better

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#239]
The audio player isn't very well aligned with the image.

Example 1 - common image size:
![image](https://cloud.githubusercontent.com/assets/1507490/13158012/d54c7f70-d658-11e5-9d25-7415c197eeff.png)

Example 2 - larger image size
![image](https://cloud.githubusercontent.com/assets/1507490/13158044/05c0ef24-d659-11e5-8455-1e9b7aa5fa30.png)

Example 3 - default image
![image](https://cloud.githubusercontent.com/assets/1507490/13158021/e19871bc-d658-11e5-9c24-2c6c5f225024.png)

Not sure what a good solution is, given that images will be different sized. I think ideally, it should be centered with respect to the image, with a small amount of spacing between the bottom of the image and the top of the player.

I notice that image, player, and transcript are all in the same bootstrap column. Maybe separating into different columns would work?

**Done when** the audio player is better aligned with the image, either as suggested above or otherwise.

**Comment by caseyedavis12** [comment]
I think ideally, it should be centered with respect to the image, with a small amount of spacing between the bottom of the image and the top of the player.


@mccalluc: I agree with your recommendation above.
