### ISSUE TITLE
Scholar Exhibits use Special Collections Layout

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#24]
@mccalluc and @Muraszko: Karen and I spoke, and we like the layout of the WGBH Special Collections a lot better than the layout of the Scholar Exhibits. We would like to use the Special Collections layout for the Scholar Exhibits instead of what Design delivered. 

The individual Scholar Exhibit page would include the 
Title
By Line below the title (as it currently appears in wireframes)
Scholar Exhibit Signature Image (to be selected & assigned to me)
Abstract
Tabs including the article, media, images, related content, and authors

**Comment by mccalluc** [comment]
implemented. Thanks.
