### ISSUE TITLE
Exhibit media: get solr queries

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#244]
Exhibit media pages should use the same machinery as the collection pages... figure out what the tags are.

**Comment by mccalluc** [comment]
@foo4thought : Would it be hard to give me a list of the possible values of `pbcoreAnnotation[@annotationType="Scholar Exhibit"]`? I could iterate over the zip and collect it... but it might be easier with the database?

**Comment by Muraszko** [comment]
@mccalluc Do you still need this?  I can send if you do.

**Comment by mccalluc** [comment]
@Muraszko : yep: there's only a dozen or so, right? So just paste it here. Thanks!

**Comment by foo4thought** [comment]
advocates
art_of_asian_cooking
bibring
boring_and_sachs
boston_civil_rights
eric_jackson
fenway_park
james_baldwin
julia_child
leary_and_jobs
needlework
new_critical_television
nine_poets
pan-african_liberation
showing_status
tech-nostalgia
tech-nostalgialeary_and_jobs
television_violence
zoom

**Comment by foo4thought** [comment]
Edit?  Record 597075 contains the wacky version of "tech-nostalgia" with "leary_and_jobs" tacked on

**Comment by Muraszko** [comment]
One record belongs to two scholar exhibits, tech-nostalgia and also leary_and_jobs.

**Comment by mccalluc** [comment]
(PR is in, and this issue was just about data collecting, so I'll close.)

**Comment by foo4thought** [comment]
I made the amalgamated value into two singular ones.  i.e., the existing pbcoreAnnotation element (annotationType="Scholar Exhibit") contains only the first value and a new additional one contains the second.
