### ISSUE TITLE
Make absolutely sure we don't need integrated management of digitization requests?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#248]
@caseyedavis12 : Could you give us a solid confirmation that email for digitization requests is sufficient? ... In particular, talking with Drew, it sounds like the system we have on OV right now was in some sense a grant deliverable, and I just want to be sure no one asks us down the road where that feature is. Thanks.

**Comment by afred** [comment]
:+1: for styling as a button

**Comment by caseyedavis12** [comment]
+ 1. If you all think it is a good idea, we could create a static page describing the costs associated with requesting digitization and transcripts.

**Comment by afred** [comment]
I like the idea of a landing page with a more verbose explanation. But I'm not sure if it would work as a static page (like an About page). It would need to receive the record ID as a parameter, and then add that param to any `mailto` link we provide.

**Comment by mccalluc** [comment]
Actually, a separate page doesn't scare me that much. Or maybe a modal on the same page?

Let's get feedback from Mike (regarding the longer email) before we go too far towards designing this.

(We should also try to keep this in our minds as a nice to have, and not something that would block release.)

**Comment by Muraszko** [comment]
This is the current automatically sent digitizing email for people requesting stuff on OV:
```
Hello,
Thank you for your interest in the digitization of WGBH Open Vault artifact <TITLE AND URL OF ARTIFACT HERE>

With Open Vault, we've added the ability to
request digitization of transcripts, audio or video.  If you agree to the pay
the digitization fee and we're able to (rights pending), WGBH will make
available the digitized audio, video and/or transcript for public access on the
Open Vault website.

If you would like to pay for the cost of digitizing, or would like more information, please email openvault@wgbh.org and we will then provide you
with a more accurate estimation of what the cost will be.

If you wish to withdraw your request for digitization of this asset,
you may do so via your profile page on Open Vault.  If we receive no
response from you for more information regarding your requests within 30 days, the requests will be
withdrawn from your profile.

If you wish for information about licensing footage from a WGBH program please contact
WGBH Stock Footage Sales at stock_sales@wgbh.org or 617-300-3939.

If you wish to view WGBH material that is not available on Open Vault, you may schedule an appointment to visit the WGBH Media Library and Archives department in Boston, Massachusetts by emailing archive_requests@wgbh.org.

Thank you for your interest in WGBH Open Vault.  Please let us know if you
have any questions.

WGBH Media Library and Archives
openvault@wgbh.org
One Guest St.
Boston, MA 02135
```

The current system of having users login and us being able to manage the digitization requests and status was not a grant deliverable.  

Using the contact us link on a non-digitized page as a catch all for requests about an asset should be fine.  It's really no different to how I'm interacting with users already.

**Comment by caseyedavis12** [comment]
@muraszko: I agree, let's stick with the current process.

**Comment by mccalluc** [comment]
modal with email links is merged. Closing this.
