### ISSUE TITLE
Is there a spec font?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#25]

**Comment by Muraszko** [comment]
[See the Style Guide](https://atlas.wgbh.org/confluence/display/OV/Style+Guide)

**Comment by mccalluc** [comment]
@afred: I'd like to assign this to you. It's less technical and more about the communication to get the web fonts, and I don't want to be the only one who has ever done this.

**Comment by afred** [comment]
Checklist (43 total):
  - [ ] Top Nav default
  - [ ] Top Nav hover
  - [ ] Carousel title
  - [ ] Button 1 default
  - [ ] Button 1 hover
  - [ ] Button 2 default
  - [ ] About Us link default
  - [ ] About Us link hover
  - [ ] Footer links 1
  - [ ] Footer links 2
  - [ ] Footer legal
  - [ ] Search index bar default
  - [ ] Search index bar active
  - [ ] Scholar exhibit button title
  - [ ] Scholar exhibit button byline
  - [ ] Collection tab button default
  - [ ] Collection tab button active
  - [ ] Inner page link
  - [ ] Share text
  - [ ] Special collections button
  - [ ] Special collections index item
  - [ ] Article download button
  - [ ] "You searched" text
  - [ ] Dropdown titles
  - [ ] Dropdown list
  - [ ] "What Is?" header
  - [ ] "What Is?" description
  - [ ] Headline 1
  - [ ] Body 1
  - [ ] Headline 2
  - [ ] H byline text
  - [ ] H byline link
  - [ ] Body 2
  - [ ] Body link
  - [ ] Headline 3
  - [ ] Body 3
  - [ ] Search Asset Label
  - [ ] Asset Date
  - [ ] Asset aspect heading
  - [ ] Body asset link
  - [ ] Body asset text
  - [ ] Citation text
  - [ ] Body related content

**Comment by mccalluc** [comment]
After the design review, I'm pretty sure the fonts are whatever they should be. Closing
