### ISSUE TITLE
Faceting by Series title not working

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#257]
i _think_ this goes beyond the fact that I don't have a full index on my dev server...

I'm seeing this in the series index...
![image](https://cloud.githubusercontent.com/assets/1507490/13188955/99a7bc9e-d722-11e5-91eb-27979f0178b4.png)

... but when I click on the link, i see this...
![image](https://cloud.githubusercontent.com/assets/1507490/13188977/c12fd684-d722-11e5-963b-7949b46349fa.png)

**Done when** clicking on links to searches faceted by series title works.

**Comment by mccalluc** [comment]
Probably just that more most series there is no content available online, and it's redirecting to the more restrictive "online" filter. PR coming soon...

**Comment by mccalluc** [comment]
So I'm thinking the user might be interested in distinguishing series that have media from those that are just metadata. The PR actually does two solr queries now, and results look like:

<img width="448" alt="screen shot 2016-02-22 at 5 39 41 pm" src="https://cloud.githubusercontent.com/assets/730388/13235380/979d1aaa-d98b-11e5-82fc-6b8d04cddfee.png">
