### ISSUE TITLE
Discuss: Impossible to turn off the "Access > Available Online" facet using the "x" control.

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#259]
Trying to turn off the `Access > Available Online` facet by using this button ...
![image](https://cloud.githubusercontent.com/assets/1507490/13189304/924642c0-d724-11e5-97f7-ccb593ca41a3.png)
... is impossible. To me, this is unintuitive and frustrating.

I've brought this up before, and I know why it doesn't work, but @mccalluc let's discuss Monday. I have an idea.

**Comment by caseyedavis12** [comment]
+1

**Comment by mccalluc** [comment]
Latest/greatest idea: 
- for "available-online" facet, don't display (css?)
- for "all", do display. (Clicking X removes the param, and then immediately there will be a redirect, but that's ok.)

**Comment by mccalluc** [comment]
It's not distinctive enough for CSS to work, but could do JS, though that seems risky/sloppy to me.
```
$("[title='Available Online']").parent().parent().hide()
```
I'll look in the view code, either to suppress output, or to add attributes at a higher level so CSS can hide it...
