### ISSUE TITLE
New DB tags for new television workshop

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#260]
(Will be breaking it into multiple tabs.)

**Comment by mccalluc** [comment]
@Muraszko : when the tags have been created, please assign me back to this.

**Comment by Muraszko** [comment]
@mccalluc Will do, Kevin and I will try and get the DB hosted today or tomorrow.  Hopefully then I can make all the data corrections currently assigned to me there.  I will assign back to you then and let you know what the newly created NTW tags are.

**Comment by Muraszko** [comment]
@mccalluc 
New tags have been created, records have been ingested.
Here is how to please assign titles to the tabs on the Special Collection NTW page:

**Dance**
```
<pbcoreAnnotation annotationType="Special Collection Tag">ntw_dance</pbcoreAnnotation>
```

**Performance**
```
<pbcoreAnnotation annotationType="Special Collection Tag">ntw_performance</pbcoreAnnotation>
```

**Video Art**
```
<pbcoreAnnotation annotationType="Special Collection Tag">ntw_video_art</pbcoreAnnotation>
```

**Data Only Records**
```
<pbcoreAnnotation annotationType="Special Collection Tag">ntw_record</pbcoreAnnotation>
```
