### ISSUE TITLE
Missing scholar collections?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#263]
There are tags supplied in #244 that don't have corresponding scholar collections
```
fenway_park
james_baldwin
leary_and_jobs
```

Maybe they're supposed to go in "From the Vault"? Take this as "double check that we have the collections and exhibits we should" rather than "All the data from filemaker must be used."

@caseyedavis12 ?

**Comment by caseyedavis12** [comment]
@mccalluc: I think it would be best to create three new scholar exhibits, in github, one for each of these. I noticed that we were missing some exhibits but I hadn't gotten around to adding these files in github. I can create the new md files in github.

**Comment by Muraszko** [comment]
Those are all Elizabeth Deane scholar exhibits.

**Comment by caseyedavis12** [comment]
Yes, with the way the exhibits are structured on new open vault, I think it would be best for each to have its own md file. And I'm rethinking using her headshot as the signature image. @muraszko: can I create three new images for you to put on s3?

**Comment by Muraszko** [comment]
Sounds good!

**Comment by mccalluc** [comment]
Done.
