### ISSUE TITLE
Set Thumbnail Display Size: Asset Search Result Pages

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#27]
Like the Stock Sales website, the already created asset thumbnails are of various sizes so they need to be cropped as they are displayed on the Asset Search Result pages to ```362 x 229px```.

NOTE- This is 1 pixel taller than the cropping required for #26 I guess because those results include a text box underneath.

**Comment by mccalluc** [comment]
search thumbnails are showing consistently, though the ratio might be tweaked, pending feedback. closing.
