### ISSUE TITLE
Short text for link-out collections

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#28]
On OV3 we have "collections" which aren't actually sets of documents. I would like to have a collection page for each which then link to the outside resource.
- Less special-casing in the code.
- Less confusing context-switching for user.

@caseyedavis12 : can you provide a paragraph or two for
- AAPB
- Stock Sales
- 10 O'Clock News

and then assign back to me? (You might have more than one link for these "collections", perhaps to particularly interesting content they contain.)

... or if you think they really-really need to link directly, not impossible.

**Comment by caseyedavis12** [comment]
Stock Sales:
WGBH Stock Sales is the clip licensing division of the WGBH Media Library and Archives. Stock Sales licenses originally shot WGBH footage and web content to television producers, publishers and professional media organizations. The Stock Sales website features over 10,000 clips and 12 WGBH collections that users can search, browse, and license. 

Search and browse thousands of WGBH clips available to license!
Click on the thumbnails below to screen examples:

BTVNDL:
The Boston TV News Digital Library, funded by the Institute of Museum and Library Services and the Council on Library and Information Resources, is a collaboration between the Boston Public Library, Cambridge Community Television, Northeast Historic Film and WGBH Educational Foundation. The website aims to bring to life local news stories produced in and about Boston from the early 1960’s to 2000.

Nearly 2,000 audiovisual news reports are available for viewing online, including content from Boston Public Library’s WHDH film collection (1960- mid-1970s), Cambridge Community Television (1988 to 1999), Northeast Historic Film’s WCVB film collection (1970-1979), and WGBH-produced The Reporters (1970-1973), Evening Compass (1973-1975) and the Ten O’Clock News. 

Click on the thumbnails below to screen examples from our collection:

AAPB:
The American Archive of Public Broadcasting (AAPB) contains approximately 40,000 hours of digitized television and radio programs selected by more than 100 public broadcasting stations throughout the nation. Nearly 12,000 programs are available for viewing and listening in the AAPB Online Reading Room. Dating from the 1940s to the 21st century, the AAPB collection includes national, local and regional programming. A collaboration between the Library of Congress and WGBH, the AAPB seeks to preserve and make accessible significant historical content created by public television and radio, and to preserve at-risk public media before its content is lost to posterity.

Browse and discover the WGBH collection in the AAPB!
Click on the thumbnails below to screen examples:

**Comment by mccalluc** [comment]
@caseyedavis12 : just make the edits you need in the MD files: I don't need to be involved.

**Comment by mccalluc** [comment]
@caseyedavis12 : text looks good. I'll leave this open for getting the sample images on the page: I'll put some stubs there, and you can change it to fit your needs.

**Comment by mccalluc** [comment]
We're hoping that there don't need to be collection-based searches with the current approach, obviating all of this. Closing.
