### ISSUE TITLE
Discuss: search result noise from records with "outside url"?

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#282]
@caseyedavis12 @mccalluc 

Since adding records with outside urls (AAPB, Boston Local News) to the group of "Available Online", some searches will now default to a lot of results that don't have an image, and you have to go somewhere else to play them.

For example, using an development index that is not complete, I searched "boston", and the first page of results had no images at all. The second page, had only 1.

![image](https://cloud.githubusercontent.com/assets/1507490/13291153/ad7e573a-dae4-11e5-8c50-533c86ff6c0d.png)

Is this something we want?

**Comment by caseyedavis12** [comment]
@muraszko: When we provide you with a list of all GUIDs for AAPB and BDVNDL content available online, can you copy the images for those items and put them in the Open Vault images folder so that they show up on Open Vault?

**Comment by Muraszko** [comment]
@caseyedavis12 Is it possible to use the Boston Local and AAPB Guids to access the thumbnails from where they are already being hosted on mlamedia01.wgbh.org (hopefully moving to S3 soon) and Amazon S3?

I can certainly do it but it would change some of the rules we've established for processing and workflow.  
Now, whenever WGBH programs are made accessible on the AAPB website in the reading room if those programs also have records on Open Vault I need to add the external URL to the Open Vault record.

If I need to also ingest the thumbnails into the OV S3 bucket, I'll first need to download them from the AAPB S3, then rename them with the OV ID and ingest it into Open Vault's S3.
It's an extra step I'd like to avoid doing if possible but I think if that's the best way to get the thumbs on there, then I'd be fine with it.  We'd also not be able to work under the assumption that any record with a thumbnail is available to be viewed on Open Vault.

Also, just thinking of how the results are structured it seems we could be highlighting content that is not available on Open Vault higher than content that is exclusive to OV.  Not that it's a huge deal, it's probably more important to point people to any of our resources, but it might be worth just making sure that's something you want to do.

**Comment by caseyedavis12** [comment]
@muraszko asked : Is it possible to use the Boston Local and AAPB Guids to access the thumbnails from where they are already being hosted on mlamedia01.wgbh.org (hopefully moving to S3 soon) and Amazon S3?


If this is possible, that would be awesome.


@mccalluc: is this possible?

**Comment by afred** [comment]
@caseyedavis12 @Muraszko @mccalluc 

The AAPB thumbs are on S3, not mlamedia01.wgbh.org. The mapping from AAPB guid to AAPB thumb is doable, via the naming convention. We'd have to whitelist openvault.wgbh.org (and any demo site) for the AAPB S3 bucket.

The mapping from Boston Local News URLs to thumbnail URLs isn't as straightforward. It doesn't look like any naming convention is used, which probably means the thumbnail URLs are just stored in Solr (i'd have to re-investigate to confirm).

I'd be in favor of moving BLN thumbs to S3 in the same manner we are doing for Open Vault and AAPB -- i.e. create a bostonlocalnew.org bucket, add the thumbs renaming them based on their record IDs. Note that the BLN IDs are non standard though.

**Comment by mccalluc** [comment]
@Muraszko / @caseyedavis12 : I think the details above are a little muddled, but maybe:

### Boston Local

http://bostonlocaltv.org/catalog/V_0EUTBAGYMADW2PP has thumbnail: http://mlamedia01.wgbh.org/bostonlocaltv/wgbh/images/barcode109558_thumbnail.jpg : no obvious way of getting from one to the other.

### AAPB

Thumbnail URLS look like: http://americanarchive.org.s3.amazonaws.com/thumbnail/cpb-aacip_283-881jx3z5.jpg -> Based on the record's URL, we can guess the thumbnail URL, which is a little sketchy, but doable.

The thing I worry about is someone doing future maintenance on AAPB: it will require institutional memory to remember that we've got this other site that is looking for the the thumbnails in a particular location. But apart from that it's doable.

**Comment by Muraszko** [comment]
Thanks for the clarification Chuck!  I guess it boils down to should the media assets be contained within their own websites?  
I think the answer is yes.  If you look at the thumbnails on the AAPB site that are for records with Boston Local or Open Vault, they are thumbnails created and hosted on AAPB's S3 retaining the same naming conventions and all that.  

If you all feel like we should just continue to follow the same practice then I think we should and I can start the process of downloading and remaining the AAPB thumbs to be stored on OV S3.

**Comment by afred** [comment]
I don't think we need to dupe the thumbs for AAPB to show them on OV.

Right now there is a reasonable convention on AAPB, which allow OV to "guess" where the thumbnails are, given an AAPB ID.

It might be better to avoid "guessing", and expose a thumbnail endpoint on AAPB that could be accessed via americanarchive.org/thumbnails/[id] or something like that. That would be easy.

The fact that we copied OV and BLN thumbs to the AAPB S3 is more of a symptom of the fact that there was not a good way to get the thumbnail URLs given an ID for those sites, at the time we needed them.

But I think "the AAPB way" is a better way going forward. If we can replicate the same pattern for the other two sites, then we get...
  1. minimal duplication of thumbnails on S3
  1. predictable locations for thumbnails that can be found by other sites as needed, using naming conventions.
  1. (and if we add an endpoint for accessing thumbnails given a record ID) a more stable way of accessing thumbs from other sites that doesn't require a "best guess".

**Comment by Muraszko** [comment]
We didn't copy OV and Boston Local thumbs to AAPB.  They are thumbs created for AAPB, but the video files were accessible outside of AAPB already so the records use the original AAPB thumbs, but link to the other sites to access the video.  Boston Local and OV have different thumb files.

I agree that using naming conventions to access external thumbs in a predictable way sounds good.  We're planning on moving Boston Local to Amazon S3, we could easily rename the thumbs at that time to their GUID as well?

**Comment by afred** [comment]
@Muraszko ah, got it, thanks!

**Comment by mccalluc** [comment]
so I've filed two bugs for the two sites, and this one can be closed.
- [AAPB](https://github.com/WGBH/openvault3/issues/286)
- [Boston Local](https://github.com/WGBH/openvault3/issues/287)
