### ISSUE TITLE
Caps in titles?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#292]
@Muraszko : This seems like a low priority datacleaning issue? There are things that could be done either at index-time or render-time, but I don't want to invest the effort here if there will be a fix upstream. (This was an ingest of only about 10% of the records.)

<img width="287" alt="screen shot 2016-02-24 at 5 09 24 pm" src="https://cloud.githubusercontent.com/assets/730388/13302747/89cdf478-db19-11e5-9217-1ff5c9859232.png">
<img width="310" alt="screen shot 2016-02-24 at 5 11 51 pm" src="https://cloud.githubusercontent.com/assets/730388/13302806/def3badc-db19-11e5-90d5-1185d1b1c7d0.png">
<img width="269" alt="screen shot 2016-02-24 at 5 14 07 pm" src="https://cloud.githubusercontent.com/assets/730388/13302849/164975e4-db1a-11e5-84ce-0a35e394198a.png">
<img width="345" alt="screen shot 2016-02-24 at 5 15 44 pm" src="https://cloud.githubusercontent.com/assets/730388/13302926/657fa656-db1a-11e5-90e4-8b12080a7ab1.png">
<img width="167" alt="screen shot 2016-02-24 at 5 17 43 pm" src="https://cloud.githubusercontent.com/assets/730388/13302965/998af4c8-db1a-11e5-8bae-5f399a13acfa.png">

**Comment by Muraszko** [comment]
Please see my response in #291 .  I'll be fixing these in the DB as part of regular grooming.

**Comment by mccalluc** [comment]
I'd like to keep this open until it's actually fixed, just so that if someone sees it in the next few weeks they know there is a plan.

**Comment by Muraszko** [comment]
Sure thing

**Comment by Muraszko** [comment]
@mccalluc 
Went through several times, fixed a lot of caps, apostrophes, and other Series duplicates.  
I'm sure there are plenty of capital Program titles, but I'll make separate tickets for those as they come up.

I'm fine with you closing this issue.

**Comment by mccalluc** [comment]
And you've reingested? I want to be sure that if we see problems on the site, they are things that still need to be done.

(If it is reingested, feel free to close.)
