### ISSUE TITLE
Search Results Sorting

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#3]
The user should be able to sort search results by relevancy, date (oldest to newest), date (newest to oldest), and alphabetically with the opening article ignored.

**Comment by mccalluc** [comment]
@caseyedavis12 : The last alphabetical sort is by item title, right? I could image sorting first by series name, then program name, then item name, but I don't want to invent things we don't need.

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, the Alphabetical sort is by item Title. It would be great if there were an option to sort alphabetically by Series Title and Program Title, in addition to Relevancy and Date.

**Comment by mccalluc** [comment]
(To be clear: I'm going to deliver the "series; program; asset" title sort. I'm not convince the others would be that useful, and I don't want to invest time on it until we know better how necessary it is.)

**Comment by caseyedavis12** [comment]
@mccalluc: On AAPB, scholars have told us that the date (Year) sorting of search results is very important.

**Comment by mccalluc** [comment]
Sorry, wanted it to be clear what kind of title sorting I was aiming for. Date sorting (new->old and old->new) is already in there and I'm not going to take it out.
