### ISSUE TITLE
Ingest errors

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#307]
@Muraszko : These are the errors I have from the latest ingest: it has changed since the last run. If any of these prove to be more involved, feel free to file bugs for individual issues. Please hold off on the checkmark until it is actually fixed in the DB.

- [x] 61 (0.1%) `PBCoreIngester::ValidationError: Attribute validation errors: Annotation: Password Restriction`
- [x] 23 (0.1%) `PBCoreIngester::ValidationError: Method validation errors: '#asset_description' failed: Empty element in XML: <pbcoreDescription descriptionType='Asset Description'>`
- [x] 61 (0.1%) `PBCoreIngester::ValidationError: Method validation errors: '#asset_type' failed: Expected 1 match for '/*/pbcoreAssetType'; got 0`
- [x] 5 (0.0%) `PBCoreIngester::ValidationError: Method validation errors: '#program_number' failed: Empty element in XML: <pbcoreTitle titleType='Program Number'>`
- [x] 1 (0.0%) `PBCoreIngester::ValidationError: Method validation errors: '#subjects' failed: Empty element in XML: <pbcoreSubject>  </pbcoreSubject>`
- [x] 481 (1.1%) `PBCoreIngester::ValidationError: Method validation errors: HTTP HEAD from #outside_url not 200: 302 Found`
- [x] 192 (0.5%) `PBCoreIngester::ValidationError: Schema validation errors: Element '{http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreAnnotation': This element is not expected. Expected is one of ( {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreTitle, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreSubject, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreDescription ).`
- [x] 1 (0.0%) `PBCoreIngester::ValidationError: Schema validation errors: Element '{http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreCreator': This element is not expected. Expected is one of ( {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreTitle, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreSubject, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreDescription ).`
- [x] 27 (0.1%) `PBCoreIngester::ValidationError: Schema validation errors: Element '{http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreGenre': This element is not expected. Expected is one of ( {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreTitle, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreSubject, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreDescription ).`
- [x] 11 (0.0%) `PBCoreIngester::ValidationError: Value validation errors: Unexpected blocked country codes: ["United Kingdom"]`

**Comment by mccalluc** [comment]
@Muraszko : here's a detailed list of all the errors. Most of them I think are data issues, but I'll look into the HTTP issues: might be doing something wrong on my end, or the HTTP checks might just not be a good idea.
[grep-log.zip](https://github.com/WGBH/openvault3/files/155065/grep-log.zip)

**Comment by Muraszko** [comment]
@mccalluc 
Do you know why the
```
Attribute validation errors: Annotation: Password Restriction
```
error is happening?
Is
```
<pbcoreAnnotation annotationType="Password Restriction">
```
Not a valid annotationType for some reason?

**Comment by mccalluc** [comment]
@Muraszko : code is just expecting plain `Password`, but `Password Restriction` is more clear. I'll change to match. Thanks!
```
  def password_required?
    xpath_boolean('/*/pbcoreAnnotation[@annotationType="Password"]')
  end
```
```
    errors += unexpected_attributes(
      'Annotation',
      [
        'Digitized',
        'Duration',
        'Geoblock',
        'Media Type',
        'Outside URL',
        'Password',
        'Playlist Group',
        'Playlist Order',
        'Scholar Exhibit',
        'Special Collection Tag',
        'Special Collection',
        'Thumbnail',
        'Transcript'])
```

**Comment by Muraszko** [comment]
@mccalluc Cool, thanks!
I just re-sent those 61 PBCore xml files that failed because of Password Restriction for you for ingest.

**Comment by Muraszko** [comment]
@mccalluc 
I just did a larger re-ingest of AAPB URLs, hoping to fix all the errors that we were getting from AAPB outside urls.  I got a new error:
```
WARN [2016-03-08 16:04:19]: 480 (34.9%) PBCoreIngester::ValidationError: Method validation errors: HTTP HEAD from #thumbnail_src not 200: 403 Forbidden
```
These 480 records all have AAPB Outside URLs and are the only records linking to AAPB.

**Comment by mccalluc** [comment]
@Muraszko : can you give me one record which reproduces the problem? Pasting the xml here would be fine.

**Comment by Muraszko** [comment]
[Open_Vault_pbCore_201638113828_xml.zip](https://github.com/WGBH/openvault3/files/163622/Open_Vault_pbCore_201638113828_xml.zip)
That's all of 480 of them, thanks.

**Comment by mccalluc** [comment]
@Muraszko : These are passing for me locally:
```
INFO [2016-03-28 10:27:49]: Processed '/Users/chuck_mccallum/Downloads/Open_Vault_pbCore_201638113828_xml.zip' 
INFO [2016-03-28 10:27:49]: success: 480; error: 0
INFO [2016-03-28 10:27:49]: SUMMARY: DETAIL
INFO [2016-03-28 10:27:49]: SUMMARY: STATS
INFO [2016-03-28 10:27:49]: (Look just above for details on each error.)
INFO [2016-03-28 10:27:49]: 480 (100.0%) succeeded
INFO [2016-03-28 10:27:49]: DONE
```

The checklist above has some validation errors outstanding; Are they still a problem, or can we close this?

**Comment by Muraszko** [comment]
@mccalluc Still busted for me.
```
INFO [2016-03-28 14:34:31]: SUMMARY: STATS
INFO [2016-03-28 14:34:31]: (Look just above for details on each error.)
WARN [2016-03-28 14:34:31]: 480 (100.0%) PBCoreIngester::ValidationError: Method validation errors: HTTP HEAD from #outside_url not 200: 302 Found
INFO [2016-03-28 14:34:31]: 0 (0.0%) succeeded
INFO [2016-03-28 14:34:31]: DONE
```

**Comment by mccalluc** [comment]
Ok, got it now: I should have actually looked at the redirect:
```
Location: http://americanarchive.org/terms/cpb-aacip_15-69m383mp
```

It's sending you to the terms-and-conditions page. I don't get that locally, because we've whitelisted wgbh addresses on AAPB. I think the simplest thing is to make HTTP checks in the ingester optional.

**Comment by Muraszko** [comment]
All fixed.  100%.
