### ISSUE TITLE
Embedded video

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#308]
On video embeds, when the user scrolls down to see the transcript, the user cannot see the video player.

![screen shot 2016-02-29 at 9 01 56 am](https://cloud.githubusercontent.com/assets/5992135/13396544/25e06d44-dec3-11e5-8a66-fca3344a42a3.png)

When the user is viewing the video player, the user can only view two lines of the transcript. 
![screen shot 2016-02-29 at 9 02 17 am](https://cloud.githubusercontent.com/assets/5992135/13396546/27cb860c-dec3-11e5-9689-c31100183c8b.png)

**Comment by caseyedavis12** [comment]
Also, not sure why this video embed has a larger player with no title on the right side like the others:
![screen shot 2016-02-29 at 9 05 49 am](https://cloud.githubusercontent.com/assets/5992135/13396609/9e30f2f0-dec3-11e5-9ad7-bae11415d170.png)

**Comment by caseyedavis12** [comment]
@mccalluc: to fix this, I would propose just removing the transcript from embedded video iframe and keeping only the player, title and Open Vault description.

**Comment by mccalluc** [comment]
@caseyedavis12 : As you are filing bugs it would help immensely to include the URLs of relevant pages so I can see what you're seeing.

**Comment by caseyedavis12** [comment]
@mccalluc: Sorry, the issue can be viewed at /exhibits/advocates




________________________________

**Comment by mccalluc** [comment]
- Tried a variety of screen widths, and not able to reproduce the issue seen in the second comment.
- Please file each bug separately. This is not a good place for meandering discussions.
- Will remove the transcript... hold on.
