### ISSUE TITLE
Select 6 items from Stock Sales, AAPB, and BTVNDL w/ screenshots

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#31]
These will go on their respective Special Collections page on Open Vault. Assigned to myself.

**Comment by Muraszko** [comment]
Hello, if you're looking for ways to include content for the Special Collections pages for AAPB and TOCN there will be 4451 asset records on Open Vault for AAPB linked material and 896 asset records for BostonLocal linked material.  You could put a link to a search results page on the Special Collection pages for each or something, unless that would be too confusing or you want to drive traffic directly to those other sites instead.

**Comment by caseyedavis12** [comment]
Thanks @muraszko: I think for these pages on the Open Vault website, the goal would be to make users aware of our other MLA website resources, so it may be most appropriate to link to items on the other sites.

**Comment by mccalluc** [comment]
Done.
