### ISSUE TITLE
Request Digitization button

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#310]
The Request Digitization tab on a record page should appear below the Request Transcription tab.

![screen shot 2016-02-29 at 9 12 05 am](https://cloud.githubusercontent.com/assets/5992135/13396788/87fea526-dec4-11e5-8e75-b3f63c247298.png)

**Comment by mccalluc** [comment]
Again, left is the media, right is the transcript, and I'm not convinced other options would be more clear.

**Comment by caseyedavis12** [comment]
@mccalluc: It's just a lot of empty space on the right of the thumbnail that I think would be better used if the options for transcribing or digitization that item were displayed next to each other.
