### ISSUE TITLE
"View Online at...." blurb

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#311]
The "View Online at" blurb should appear to the right of the thumbnail icon instead of below it.

![screen shot 2016-02-29 at 9 13 41 am](https://cloud.githubusercontent.com/assets/5992135/13396848/cb808d1e-dec4-11e5-8f89-4316a36488c4.png)

**Comment by mccalluc** [comment]
@caseyedavis12 : Is there any motivation for this change? Right now there's a logical division on the screen between the the player/thumbnail/view-online-link to the left, and the transcript/request-transcript to the right. Doing it differently would be harder to maintain, and I believe more confusing. Talking in person might be better.

**Comment by caseyedavis12** [comment]
@mccalluc: maybe I'm the only one, but the "View Online At..." text below the thumbnail doesn't really stand out. With it appearing below the thumbnail, it kind of meshes into the other metadata fields below it.


I just think that the information about the video such as requesting digitization, requesting transcription, and the View Online At blurb would be more visible in the blank space to the right of the thumbnail. it would also be a better use of all of that blank space, IMO. @afred or @muraszko feel free to weigh in.
