### ISSUE TITLE
Missing line breaks in embedded transcripts?

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#315]
I just noticed it in the screenshot from #314:

https://cloud.githubusercontent.com/assets/730388/13406456/9aa79944-def1-11e5-9d2a-f71d95d22407.png

**Done when** appropriate line breaks are displayed -- OR -- this is determined to be a data issue.

**Comment by mccalluc** [comment]
The text below the title isn't the transcript, it's the description.
