### ISSUE TITLE
Is there item-to-item linking between OV and other sites?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#32]
@caseyedavis12 : On AAPB we have the links to outside sites, for instance MPR... Do we need something analogous here to link to individual records on bostonlocal or AAPB? Or is it a reach goal? Or is it unneeded?

**Comment by Muraszko** [comment]
There are metadata fields in the OV PBCore that contain Boston Local UID and AAPB GUIDs for asset records on those sites.
