### ISSUE TITLE
"Right" way to (re)ingest

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#333]
@afred : should there be (or is there already) a capistrano task for indexing and restarting rails? .... and maybe another one that returns a log-file name which can be used as an argument to a second task which either scps the log to your local machine, or fails if the ingest is not complete?

(Right now, the ingest log name is not stable: perhaps it should be.)

**Comment by afred** [comment]
I'd be in favor of a more stable log filename, e.g. ingest.[timestamp].log, and adding the parameters used to invoke the ingest somewhere in the log.

To run an ingest: `cap [stage] ingest:run OV_PBCORE=path/to/local/pbcore_file`

Currently, this will look for `pbcore_file` in a predetermined location on the remote machine, and run an ingest on it. (I'm hoping to make this less magical with [this ticket](https://github.com/WGBH/openvault3_deploy/issues/31)).

To restart rails `cap [stage] deploy:restart`, which is a generic shortcut to `cap [stage] passenger:restart` -- both do the same thing.

+1 for adding something like `cap [stage] ingeset:download_log`.

**Comment by mccalluc** [comment]
Closing this: actually capistrano work. See 
- https://github.com/WGBH/openvault3_deploy/issues/31
and
- https://github.com/WGBH/openvault3_deploy/issues/32
