### ISSUE TITLE
Transcript search instruction 

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#339]
Karen said that the transcript search instruction is confusing and gets covered as you scroll down the transcript. She also said that the symbol is not universally recognizable and is not intuitive. 

Can we put the transcript search instruction in a place that is not part of the scrollable transcript? Also, can we rethink the messaging of the instruction?

**Comment by mccalluc** [comment]
- You're right, it's not universal: On windows, it's "control", and we do browser sniffing to print out the right message: if that doesn't seem to be working for you, let me know.
- If some other text would be better, let me know what it is. It should not be longer than one line: Making things longer does not make them more clear.
- I'll put an "X" to the side of the box so it can be closed, and a cookie will remember that.

**Comment by mccalluc** [comment]
@caseyedavis12 : Does the screen shot at #342 look any better?

**Comment by caseyedavis12** [comment]
@mccalluc: Looks good to me. Thanks you!
