### ISSUE TITLE
ingest --email

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#345]
We want to be able to specify an email address when starting an ingest, so that there can be a notification on completion. Currently, the wgbh outlook server does not seem to be accepting the emails my script would send. Have filed a help ticket: http://servicedesk.wgbh.org/scripts/texcel/servicewise/clogin.dll?cqedit?xEmoyigiixomkjwihggd

**Comment by mccalluc** [comment]
To summarize, our logs say:
```
... to=chuck_mccallum@wgbh.org, delay=00:00:26, xdelay=00:00:05, mailer=esmtp, pri=120008, relay=wgbh-org.mail.protection.outlook.com. [207.46.163.215], dsn=5.7.606, stat=User unknown
... DSN: User unknown
```

[IT says](http://servicedesk.wgbh.org/scripts/texcel/servicewise/clogin.dll?cqedit?xEmoyigiixomkjwihggd): 
>
SMTP is blocked/filtered by AWS for all EC2 instances to prevent spamming. The recommended way to send email from an EC2 instance would be to setup SES, and relay your mail through SES. If the volume of email is very,very small, you can give the instance an Elastic IP and make a support request with AWS to allow SMTP. 

[AWS says](https://aws.amazon.com/ec2/faqs/#Are_there_any_limitations_in_sending_email_from_EC2_instances):
> 
Yes. In order to maintain the quality of EC2 addresses for sending email, we enforce default limits on the amount of email that can be sent from EC2 accounts. If you wish to send larger amounts of email from EC2, you can apply to have these limits removed from your account by filling out this form.

@afred: I am not convinced that the error we have is generated by AWS; might be, but the docs don't say outright that sending mail is impossible from EC2. In any event, there is some limit, and it would probably be frustrating to bump into that and not receive notifications.
- Explore SES?
- Abandon this approach / user pings to check for completion?

**Comment by afred** [comment]
@mccalluc let's take a peek at SES. In general, I think knowing how to have our AWS hosted websites send emails is worth a little investigation.

**Comment by afred** [comment]
@mccalluc I actually just requested verification of the `wgbh-mla-test.org` domain with SES. Currently says it's pending.

https://console.aws.amazon.com/ses/home?region=us-east-1#verified-senders-domain:

**Comment by mccalluc** [comment]
... seems to be approved now.

**Comment by afred** [comment]
right on, not sure what the next steps are. If you want to jump on this, feel free.

**Comment by mccalluc** [comment]
Looked into this a bit further: It looks like in order to send email you need to create a new IAM user with limited privs: This produces credentials which we wouldn't want to check in... So either they'd need to be passed with another environment variable, or they'd be another resource which aws-wrapper would handle the creation of. Neither really appeals to me right now.

(I've created the credentials and stored them locally, and I've done a test email.)

**Comment by afred** [comment]
Right on, thanks for the investigation. I imagine we'll want to send emails from a web app hosted on AWS at some point... but for now, maybe just stick with the option to [add a cap task to download the log](https://github.com/WGBH/openvault3_deploy/issues/32).

**Comment by mccalluc** [comment]
closing for now, but in the future we might revisit.
