### ISSUE TITLE
--stdout-log no longer working

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#368]
```
$ ruby scripts/ingest.rb --stdout-log --same-mount --files ~/Downloads/2015_OV_MASTERS_FINAL_pbcore\(1\).zip
logging to /Users/chuck_mccallum/starting/openvault3/log/ingest.2016-03-07_161413.log
```
@afred? Maybe at this point it's not really that necessary, and it'd be better to get rid of it than to get it supported again?

**Comment by afred** [comment]
@hmm.. I definitely remember coding around the switch that said stdout. Let me take a quick peek, may be an easy fix. Timeboxing to 10 min, stand by.
