### ISSUE TITLE
Records for items on AAPB & BTVNDL

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#37]
Below the thumbnail icon on record pages for items available to view/listen on AAPB & BTVNDL, provide the following hyperlinked text:

If video:
View online at American Archive of Public Broadcasting
View online at Boston TV News Digital Library

If audio:
Listen online at American Archive of Public Broadcasting
Listen online at Boston TV News Digital Library

You will know if an item is available on AAPB or BTVNDL if there is a pbcoreAnnotation type="Outside URL" in the PBCore record. The value of the annotation will be the URL to that record on AAPB/BTVNDL.

**Comment by mccalluc** [comment]
Duplicates #32. closing
