### ISSUE TITLE
AAPB Example points back to ov

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#374]
- http://localhost:3000/collections/american-archive-of-public-broadcasting, " Remembering James Brown" ->
- http://americanarchive.org/catalog/cpb-aacip_15-3n20c4t26j ->
- http://openvault.wgbh.org/catalog/openvault:1696

We shouldn't point to AAPB, only to point back at OV.

**Comment by caseyedavis12** [comment]
@mccalluc: Just fixed in latest PR

**Comment by mccalluc** [comment]
@caseyedavis12 : The James Brown link is still there. (Not sure which PR should have fixed the problem, but in the future, including issue numbers in commits and PRs would be a way to make those connections.)

**Comment by caseyedavis12** [comment]
@mccalluc: See PR #499

**Comment by mccalluc** [comment]
Thanks!
