### ISSUE TITLE
Vietnam transcript only records: gone, and maybe never were there

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#384]
http://openvault.wgbh.org/collections/vietnam-the-vietnam-collection lists a number of transcript only records. These are all 404 right now, on the old site.
>
    Astor Rogers (transcript only)
    Daniel Ellsberg (transcript only)
    David Ross (transcript only)
    Don Luce (transcript only)
    Douglas Hostetter (transcript only)
    James N. Rowe (transcript only)
    John T. McAllister (transcript only)
    Mark Smith (transcript only) [2]
    Orrin DeForest (transcript only)
    Ted Danielsen (transcript only)
    Tran Ngoc Chau (transcript only)
    William D. Ehrhart (transcript only) [2]

- Should we have anything for these on the new site? 
- Do we even know where they are? 
- Would we have any obligation to funders to make these available going forward?

@caseyedavis12 or @Muraszko ?

**Comment by Muraszko** [comment]
Looking into this.

**Comment by Muraszko** [comment]
Weird, I'm able to find the records, so I will create new xml and ingest it.

@mccalluc It looks like these files have a thumbnail and a transcript, but no proxy.  Do you think it will throw the display of the transcript off because it has nothing to sync to?
Wait and see until ingest?

**Comment by Muraszko** [comment]
@caseyedavis12 @mccalluc 
Just did one:
http://ov-qa1.wgbh-mla-test.org/catalog/V_24DE6CA361564377B38500FF1CFF8A8C

Looks ok to me using the default video, no thumb image.

**Comment by caseyedavis12** [comment]
@muraszko: looks good to me. Thanks!

**Comment by Muraszko** [comment]
All uploaded and verified.
