### ISSUE TITLE
We have none of the outbound links that the old site had per collection

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#385]
Taking *Vietnam* as an example: There were links provided to
-    American Experience: Vietnam
-    Teachers' Domain: Vietnam War
-    Veterans History Project, a project of the American Folklife Center of the Library of Congress
-    UMass Boston Vietnam Finding Aid
-    Shop PBS

In addition the old footer credits linked to, instead of simply listing, these:
-    IMLS (also had logo)
-    University of Massachusetts Boston
-    The William Joiner Center of the University of Massachusetts Boston
-    Columbia University: Columbia Center for New Media Teaching and Learning
-    Footage Courtesy of ABCNews
-    Footage Courtesy of CBS News

@caseyedavis12 : can you confirm that this is an intentional change and not just an oversight?

**Comment by caseyedavis12** [comment]
@mccalluc: Not an oversight, just hadn't gotten to it yet. Related content has been added in multiple PRs.


Credits and logos are intentionally being added to the /credits/credits-.. pages.

**Comment by mccalluc** [comment]
Vietnam seems to be done. I'll assume all the work in the area is complete and close, but @caseyedavis12 if you know that there are outstanding TODOs please open new bugs so we know what is outstanding.
