### ISSUE TITLE
Why are we keeping the blog?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#386]
There has not been a post in over a year. If we are not using it, we should simply kill it instead of letting it linger indefinitely.

**Comment by Muraszko** [comment]
With the redesign there is work planned to make better use of the blog as a place for longer MLA communications and more frequent updates.

**Comment by caseyedavis12** [comment]
Creating new Wordpress blog is on my to-do list.

**Comment by caseyedavis12** [comment]
Muraszko and I spoke, and we plan to modify the look of the current wordpress blog. On my to-do list.

**Comment by mccalluc** [comment]
ok
