### ISSUE TITLE
vietnam footage database?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#388]
http://openvault.wgbh.org/sfdb/about/intro.html exists. I find it completely useless. If we are not going to port it, that should be an explicit decision, rather than just letting it fall through the cracks.

**Comment by mccalluc** [comment]
@caseyedavis12 / @Muraszko : I had happy not to port this. Ok?

**Comment by Muraszko** [comment]
@mccalluc @caseyedavis12 
We're not porting over the current footage database.  Thanks Chuck.

**Comment by mccalluc** [comment]
yay!
