### ISSUE TITLE
MPOT?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#389]
http://openvault.wgbh.org/media-production-organizational-tools/

- Are we doing this?
- If so, where is it linked from?
- MD already exists, but
- move resources to S3

Also, the zip that is currently up for MatUsed is broken: only 700 bytes, and when unzipped does not produce a database, unsurprisingly.

**Comment by caseyedavis12** [comment]
@mccalluc: I added the link to the footer.

**Comment by mccalluc** [comment]
Link in footer. MATUSED still broken, will file new.
