### ISSUE TITLE
Treatment in header when you're under one of the three links?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#39]
For the sake of context, should there be a change in the header when you are under exhibits or collections? Like, make the active one bold and not a link?

**Comment by caseyedavis12** [comment]
@mccalluc: Great idea, sounds good to me. Will it remain not linked when a user is in an individual exhibit or special collection? I guess that would be fine since the user can return to the exhibit/special collections index using the breadcrumb above the title.

**Comment by mccalluc** [comment]
Going to drop this: the link above the title is prominent enough, and I don't want to get into tweaking the design.
