### ISSUE TITLE
Assessment PDF?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#390]
/credits/credits-open-vault-research.md references but does not actually link to the 128 page PDF currently at http://openvault.wgbh.org/pdf/WGBHMLAAssessment.pdf

- Is URL stability important?
- Or can it be put on S3?
- (If so, we will need to add a special case to our referer checking: This should not be restricted.)

**Comment by caseyedavis12** [comment]
@mccalluc: I will be putting all of the project reports on S3.

**Comment by mccalluc** [comment]
@caseyedavis12 : I believe this report is now on S3, but there is no link from any MD file to it.

**Comment by caseyedavis12** [comment]
@mccalluc: yes, that and two other reports are being reviewed again by legal. Not a blocker though.
________________________________

**Comment by mccalluc** [comment]
http://openvault.wgbh.org/credits/credits-open-vault-research links to the 3 PDFs, so I think this is done, now.
