### ISSUE TITLE
Logos broken / missing

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#391]
http://ov-qa1.wgbh-mla-test.org/credits has broken images right now. They must be provided, or the links removed.

The other credits pages used to have logos and no longer do. I do not know whether this an intentional change or an oversight.

**Comment by caseyedavis12** [comment]
I have meetings scheduled with Karen and Foundation Development to review all of these pages on Thursday. More mds will be added since a few projects are missing from the list. We are waiting on logos from a couple of foundations. Some logos have been added this morning.

**Comment by mccalluc** [comment]
Logos are in and commented out. Can be uncommented whenever folks think it is clear with legal, but I'll go ahead and close this because nothing is broken right now.
