### ISSUE TITLE
Search results facets

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#4]
As a user on a search results page, I see the following facets above the search results in this order from left to right:

Access (digitized & online as default)
Media Type (sound, video, image)
Year and year range (see AAPB)
Asset Type
Genre 
Topic

**Comment by mccalluc** [comment]
@caseyedavis12 : 
- putting year on the far right solves some real estate problems, so I'll do that unless there are strong objections.
- Filed #126 for date-range slider. Currently not milestoned: add it to one if you feel it's a priority.

**Comment by caseyedavis12** [comment]
@mccalluc: I don't have any objections to putting the year on the far right.

**Comment by mccalluc** [comment]
With #149, I think this is complete. Re-open if there are tweaks.
