### ISSUE TITLE
What should be the behavior when you submit an empty search? / Or no search results?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#40]
FWIW:
- google/bing/yahoo/baidu do nothing on empty search.
- aapb list all online assets.
- stocksales goes to a plain error/search page.

**Comment by caseyedavis12** [comment]
@mccalluc: show all online assets

**Comment by mccalluc** [comment]
@caseyedavis12 : by "online" we mean records with playable media + image records?

I strongly believe that is **not** the behavior we want if there are no matches.

**Comment by caseyedavis12** [comment]
@mccalluc: I agree; if the user submits an empty search, show all "online" records (playable media + image records)


If the user submits a request which retrieve zero search results, then show the same message that appears on AAPB:


No entries found

Consider using other search terms, removing filters, or searching all records, not just those with media.
