### ISSUE TITLE
Stock sales images are uneven

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#406]
#382 brought in 6 thumbnails for stock sales, but they aren't the same size, and the result is pretty ugly. Appropriately sized images on S3 will fix this; there doesn't need to be a PR.
<img width="851" alt="screen shot 2016-03-09 at 12 32 16 pm" src="https://cloud.githubusercontent.com/assets/730388/13644428/c3f2a54c-e5f3-11e5-87f8-f53cf023a5d3.png">

**Comment by caseyedavis12** [comment]
@mccalluc: fixed.
