### ISSUE TITLE
Discussion: Available Online: Content on AAPB and BTVNDL

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#414]
BTVNDL = Boston TV News Digital Library

Since a default search on Open Vault shows only content that is available online, I think it would be good to include records for content that are available to view online at AAPB and BTVNDL in the "Available Online" facet. We would also need to edit the Series page to show the number of programs available online in series available at AAPB and BTVNDL.

**Comment by Muraszko** [comment]
@caseyedavis12 
I think it already does.
If you search for Boston, most of the results on the page are for BLTV.  And on the series page:
![screen shot 2016-03-10 at 11 08 21 am](https://cloud.githubusercontent.com/assets/6650285/13675603/6c885028-e6b0-11e5-9a40-8a4ed20c3912.jpg)

**Comment by caseyedavis12** [comment]
@mccalluc: Oh, I searched for "WGBH Journal." There are 175 programs available online at AAPB. None are available on Open Vault.

**Comment by Muraszko** [comment]
@caseyedavis12 
There are still 480 records (All the AAPB external URL records) that are giving us errors on ingest.
#307 
Once those are successfully ingested then they should show up and work just like the Boston Local records.
Keep in mind, there are only 480 records in the AAPB online reading room that overlap with records on Open Vault.  So those are the only ones that will show up.

**Comment by mccalluc** [comment]
So I think we're all on the same page about having AAPB and BTVNDL count as online, and that code is already live, so I'll go ahead and close this? Thanks for noticing.

(While we're here: The series list is a little odd in this regard: If a given series has both online records, and records which are not online, the count it gives is only the former. We could potentially display both numbers, but that seemed more confusing than useful.)
