### ISSUE TITLE
Verify Google Analytics tracking code

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#421]
**Done when** confirmed whether or not google analytics is working on the new site.

**Comment by Muraszko** [comment]
Looks like it's working correctly, you can see the URLs are using the new OV ID:
![screen shot 2016-03-22 at 1 42 46 pm](https://cloud.githubusercontent.com/assets/6650285/13961702/10409568-f034-11e5-8a02-d1873fa86b92.jpg)
