### ISSUE TITLE
Records missing from display on Vietnam Collection

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#427]
For interviewees that have two interview records, the second interview isn't displaying on the Collection page for Vietnam.

This is not related to "Part 1 of 2" kinds of records, these are the "Interview with John Smith [1]" records.

See Tho Hang, 1981:
![screen shot 2016-03-11 at 10 41 23 am](https://cloud.githubusercontent.com/assets/6650285/13707059/e006b77c-e775-11e5-8ac3-b4fb4faad435.jpg)

But in the search results, you'll find there are two interviews with him:
![screen shot 2016-03-11 at 10 42 13 am](https://cloud.githubusercontent.com/assets/6650285/13707081/f46e14bc-e775-11e5-8300-7616916dd08c.jpg)

The [2] records have the same metadata tags to be put in the interview tab:
```
<pbcoreAnnotation annotationType="Special Collection Tag">vietnam_interview</pbcoreAnnotation>
```

So I don't think it's a metadata issue.

**Comment by mccalluc** [comment]
@Muraszko : feature, not a bug. :) 
tabbed.rb:
```ruby
        solr_docs.reject do |solr_doc|
          solr_doc['short_title'].match(N_OF_N) && !solr_doc['short_title'].match(ONE_OF_N)
          # Details pages will provide navigation between parts.
```
With the list being as long as it already is, the idea is to keep it as tight as possible. It's unlikely that someone just browsing the list will see "John Doe, part 3 of 5" and say "I MUST HAVE THAT", when plain "John Doe" wasn't of interest.

(Once they get to the record, they should be able to page to the next one is the sequence, so it's still there.)

Ok? Can this be closed?

**Comment by Muraszko** [comment]
I figured, just wanted to make sure.  
They can also navigate up to the search results page from the individual record page by clicking on the Interviewee's name or searching their name.  Fine with me.
Thanks!
