### ISSUE TITLE
Choose items for homepage carousel

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#43]
- Resize and upload images to S3
- Put images / hrefs / text in carousel.md.

**Comment by mccalluc** [comment]
@caseyedavis12 : Could you prioritize this over the content edits? It is essential for launch, while the static pages have been the way they are for a long time, and they could be stale a little longer with no harm done.

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, I will prioritize this today.

**Comment by caseyedavis12** [comment]
@mccalluc: the specs and wireframes don't specify the size of these images. Do you know what size they should be?

**Comment by mccalluc** [comment]
@caseyedavis12 : I can't speak to "should", but currently, with the widest window widths it is 1140 pixels, and the mockup has an aspect ration of approximately 2:1... but when we actually look at a screen that large, we have problems, I think:
<img width="1240" alt="screen shot 2016-02-29 at 11 47 46 am" src="https://cloud.githubusercontent.com/assets/730388/13402273/8f1b75be-dedd-11e5-949a-12972475859a.png">

I don't think it's good to use this much real estate on the carousel... but that's just my opinion.
- Is there a problem? Maybe not. Your call...
- If there is, who should own how it gets fixed? us / design?
- If there is a problem, and we should take ownership, I could make a proposal... but I don't know that either of those conditions is true.

**Comment by caseyedavis12** [comment]
@mccalluc: Do you think that the rotating gallery that we use on AAPB would be better? What proposal do you have in mind?

**Comment by mccalluc** [comment]
I don't want to be the one to say whether there is even a problem in the first place. That's not my call.

**Comment by caseyedavis12** [comment]
@mccalluc: I think that the 1140 x 340 image takes up too much space; that's why I asked.

**Comment by mccalluc** [comment]
proposal: At the widest screen width, only use the middle 2/3 of the page, so something like this: (Real thing will include the normal text, and arrows will be positioned correctly.) Keep the 2:1 aspect ratio.
<img width="1246" alt="screen shot 2016-02-29 at 1 08 41 pm" src="https://cloud.githubusercontent.com/assets/730388/13404046/e8f78264-dee5-11e5-8d48-0f679ffd451b.png">

Other possibilities:
- Status quo (screen shot in original post): Neither of us really like that...
- Something like stock sales... but we'd need something to fill up the space to the right? Probably not a good idea...
- Make the image progressively squatter on wider screens: so 3:1 instead of 2:1? Knowing how to crop an image so it still works in that form is hard... and would we need to maintain multiple versions, at different aspect ratios?

**Comment by caseyedavis12** [comment]
@mccalluc: so you don't think that reusing the rotating gallery code from AAPB would be a good idea?

**Comment by caseyedavis12** [comment]
@mccalluc: If not, let's just stick with 1140 x 340 images and get Digital's input.

**Comment by mccalluc** [comment]
@caseyedavis12 : not sure where the 340 came from: I think images 2:1 would be reasonable. Also, I don't think images need to be the full pixel width+height, but your call.

**Comment by mccalluc** [comment]
@caseyedavis12 : if you haven't already, please prioritize this: you could wait to crop the images, but there's nothing we should be waiting on to 
- select X items, and for each
- choose an image
- title text
- link target
- and put it all in a PR

**Comment by caseyedavis12** [comment]
@mccalluc: Already working on this.

**Comment by caseyedavis12** [comment]
@mccalluc: I uploaded all but one image to s3. Waiting on Stock Sales logo and will put that up as soon as I receive it.

**Comment by mccalluc** [comment]
The current set works. Closing.
