### ISSUE TITLE
Use images in logo instead of svg

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#430]
**Done when** we have suitable images for logos that are not blurry at various resolutions.

**Comment by mccalluc** [comment]
The argument made in the meeting for reverting from the SVG was consistency. The only other place the logo appears on the site is in the watermarks, but they look like something else entirely:

<img width="724" alt="screen shot 2016-03-15 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/730388/13790450/e0ab21bc-eabe-11e5-9e2b-49b31250fbaa.png">
- bold and thin are swapped
- both words are lowercase
- but line heights do not match

We don't want to return to that, so if there's a problem with the SVG we should articulate what it is.

**Comment by caseyedavis12** [comment]
@mccalluc: I don't think there is a problem with sticking with what we have (svg).

**Comment by mccalluc** [comment]
okey-dokey

**Comment by afred** [comment]
Fwiw.. i don't think the lack of consistency was the issue with the SVG.... rather I think the lighter-weight text in the SVG logo (i.e. the "open" part of "openvault") is more spaced out than in the rastered logo.

But.. yeah, no strong opinions here.
