### ISSUE TITLE
Keep header links on mobile

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#432]
**Done when** nav links stack for mobile like so

![image](https://cloud.githubusercontent.com/assets/1507490/13711873/c7101772-e78e-11e5-9258-d596921e4521.png)

**Comment by mccalluc** [comment]
I think we're on the same page that there just isn't room for including all those links on every page on mobile: Do we really want every one of our pages to look like that screenshot, with the actual page content not coming till an inch from the bottom? Closing.
