### ISSUE TITLE
Homepage element padding adjustments

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#435]
In our meeting, we deviated from the the suggestions listed [here](https://atlas.wgbh.org/confluence/display/OV/Open+Vault+Design+QA). Below are the specs we decided on.

**Done when**
  * 66px spacing between the dark gray box and text above it
  * 66px spacing between bottom of carousel and top of yellow buttons
  * padding 40px all around on dark gray box
  * 80px padding dark gray box
  * **bold** titles within dark gray box

**Comment by mccalluc** [comment]
@afred : Do you remember what the intention was here?:
>
- padding 40px all around on dark gray box
- 80px padding dark gray box

One of those should be a margin, I think, but which?

**Comment by afred** [comment]
@mccalluc hmm.. yeah, I'm guessing the 40px is the legit one for the dark dray box. Don't remember what what the 80px is alluding to. Maybe that's what the original recommendation was, and then we adjusted it down to 40, but I forgot to delete the 80px?

The 66px is only for the spacing between the _top_ of the gray box and the bottom of the text below the yellow boxes. I assume that `top-margin` on the dark gray box is appropriate.

**Comment by mccalluc** [comment]
I think this has all been done.
