### ISSUE TITLE
Fix metadata Records

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#46]
Fix metadata, Contributor for the following OV records

```
V_38B4E344B4B34969A5BEA2ED170A1000
```
- [x] ingested

**Comment by Muraszko** [comment]
Add asset type for these records:

[add_asset_type.csv.zip](https://github.com/WGBH/openvault3/files/96200/add_asset_type.csv.zip)

**Comment by Muraszko** [comment]
Change Geoblock annotation for "GB" for these records:
```
V_4D37F2D8E1054BA49999027BF9D18957
V_0E198C52126E4300B523C24B468F093F
V_7C97C4381B7849D791CD357588C2FE89
V_7CCEDE8F8CE246889EBAAB8BCB225EB5
V_F35B306F7C624DD7A10E24D65FD907C2
V_D9DC82D997454711A71B586E17D23119
V_68EC0BDF4C59474F80F6A9E7222A5943
V_AD9E0BC353BF435E83F28DEF165D4F40
V_A77C972F922248CB81348270B1FA8AE2
V_9B8EDE8E69794C41B5D417FFA1C9940F
V_EC93438EE8A747989743A3987DD21409
```

**Comment by Muraszko** [comment]
Add empty
```
pbcoreDescription   descriptionType="Asset Description"    
```
For all 220 of these records:
[add_description.csv.zip](https://github.com/WGBH/openvault3/files/124940/add_description.csv.zip)

**Comment by Muraszko** [comment]
Capitalize FRONTLINE Series title for these records.
```
V_12B219911CAE4B47B0FF5BBC420F16D3
V_2D620BE7592249339CDFAB890B33D9C1
V_3EAD40516820401EB09229BA34801557
V_4CB3966E266B4A1CAD8132AD2B294731
V_5328571CCA034977ADF8718B0966B57E
V_AC8281BA9D7B494FB596E55D15C52B90
V_C207405E9C064B0E9B2FD9E4FBFFC927
V_DF11C4A27D1941F7BD3F8208D6A4C24C
V_E0657588080F4B468DA3E9A611FC5F85
V_E96C138ECE97468BA557DDDBA6440706
```

**Comment by Muraszko** [comment]
Capitalize NOVA series title for these records.
```
V_197FE55774B148DB9D0A7D43C7F9913A
V_3255D385EF7648FC89BD4CA690E9ED6B
V_677D26C6C1DB412FA2EB938AD7F788E3
V_EB2B39845378498CAB56C875734BD7A0
```

**Comment by Muraszko** [comment]
Change Series title to Africans In America  (capital I)
```
V_7911A6D50AF341BDAE7466E223920A2F
```

**Comment by Muraszko** [comment]
For whole programs (Nova frozen addict and all the advocates online) remove the Open Vault Title so the records look better.
Right now the search results show up like "Advocates; Program ABC; Program ABC" the last Program ABC is the Open Vault Title.

**Comment by mccalluc** [comment]
@Muraszko : It might be good to keep bugs more granular, just so that when we mark something as fixed, we'll know exactly what's in scope. Another alternative is to use the checkboxes. Your call.

**Comment by Muraszko** [comment]
I agree.  This ticket is for data issues that I want to have completed for the launch.  Any future ones will have their own new issues created on Github or elsewhere.
