### ISSUE TITLE
Demonstrate a redeployment and swap

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#466]
**Done when** we have working, up-to-date websites at both "openvault.wgbh-mla.org" and "demo.openvault.wgbh-mla.org" after redeploying and running the aws-wrapper script to perform the swap between "demo" and "production".

steps:
  - [x] deploy latest to "demo" only and verify
  - [x] initiate swap
  - [x] verify "production" contains latest

**Comment by afred** [comment]
@mccalluc The swapping work very well, great work!

The rsync doesn't work for some reason though. But it doesn't need to for the immediate time being.

I'm still not totally sold that we need that final rsync step. Or at least, I like the idea that we can swap without doing the rsync. The swapping is very fast, and a full rsync will probably be very slow. So the idea that we can swap without rsync, and then swap quickly back if we made a mistake is very appealing.

I nice flow might be:
  1. deploy to demo
  1. verify
  1. swap
  1. verify
  1. rsync if desired

Thoughts?

(closing this ticket now though, because it's done)

**Comment by afred** [comment]
Here's what's happening with the rsync... no errors, just not finding any files I guess...
```
INFO [2016-03-18 09:17:05]: try 1: ssh -A -o StrictHostKeyChecking=no ec2-user@54.161.200.149 -t -t 'if [ -e /mnt/ebs ]; then rsync -ave '\''ssh -A -o StrictHostKeyChecking=no -l ec2-user'\'' --exclude=lost+found ec2-user@54.147.250.247:/mnt/ebs/ /mnt/ebs/; fi'
INFO [2016-03-18 09:17:06]: receiving incremental file list
INFO [2016-03-18 09:17:06]: 
INFO [2016-03-18 09:17:06]: sent 27 bytes  received 42 bytes  138.00 bytes/sec
INFO [2016-03-18 09:17:06]: total size is 0  speedup is 0.00
INFO [2016-03-18 09:17:06]: Connection to 54.161.200.149 closed.
```

**Comment by mccalluc** [comment]
@afred: If I remember correctly, the rsync is only looking at the EBS volume, which, AFAIK, we're not using, so no surprise that nothing is being copied.

More generally: maybe it doesn't fit our workflow that well. The alternative would be taking responsibility for making sure any new deploy has a fresh index, and fresh code, and maybe that works better for us?

The other part of this question is whether we ever update code or index on the live server... If we do, then I could imagine it being more likely that the other server lags, and we might swap it up while it's still behind.
