### ISSUE TITLE
Have IT change DNS

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#467]
Latest contact for doing this is ryan_groth@wgbh.org

**Wait for #465 and #466 before doing this!**

**Done when** a CNAME records points `openvault.wgbh.org` to `openvault.wgbh-mla.org`

**Comment by afred** [comment]
ticket filed with servicedesk, incident ID 54776

**Comment by mccalluc** [comment]
URL: https://servicedesk.wgbh.org/scripts/texcel/servicewise/Customer/Conversation.dll?projectid=58&bugid=54776

**Comment by caseyedavis12** [comment]
@mccalluc: I don't have access to this IT ticket. Can you let me know when it is resolved?

**Comment by mccalluc** [comment]
@caseyedavis12 : It's a Terrible, Horrible, No Good, Very Bad web app. Login at https://servicedesk.wgbh.org and then try the URL above. (Or not: nothing has changed.)

**Comment by afred** [comment]
@caseyedavis12 @mccalluc @Muraszko done! http://openvault.wgbh.org
