### ISSUE TITLE
Special Collections Interview Sorting

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#47]
The way we're anticipating the display of the Special Collections to look is like this:
![screen shot 2016-01-12 at 9 14 23 am](https://cloud.githubusercontent.com/assets/6650285/12265735/e367c6fa-b90c-11e5-9463-c772a35240c4.jpg)

But it has not been clear as to how we'll sort the interviews alphabetically.

Now that the data is getting locked down, I'd be comfortable with sorting the Special Collection interviews alphabetically using:
```
Contributor
contributorRole="Interviewee"
```
Then sorting by the Contributor value, which should follow Last name, First name 

If there are multiple Interviewee Contributors for an individual record, use the first one you find to sort on, if possible.

**Comment by caseyedavis12** [comment]
+1

**Comment by caseyedavis12** [comment]
@mccalluc: Why is this post launch? Are you waiting for me to make a decision?

**Comment by mccalluc** [comment]
@caseyedavis12 : No: only that if getting the site out sooner matters at all, then some things that hardly anyone will notice can be left till a little later... but if you disagree, feel free to change the milestone: just means release will be a bit later.

**Comment by mccalluc** [comment]
Fixed with https://github.com/WGBH/openvault3/pull/160/files#diff-12e6136113dd34dc99c9fad0cefe8370R87
