### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#478]
The site does not look good on mobile, and recent design changes (tons of white space, more links in the header) are making it worse.

<img width="1147" alt="screen shot 2016-03-15 at 11 27 28 am" src="https://cloud.githubusercontent.com/assets/730388/13783388/a13f9a2a-eaa1-11e5-83c4-9cbc93c07b2c.png">

**Comment by caseyedavis12** [comment]
@mccalluc: Can I see what the mobile site looks like with recent design changes implemented?

**Comment by mccalluc** [comment]
I think it looks good enough now. Reopen or file a new one if you think more work is needed.

<img width="326" alt="screen shot 2016-05-05 at 2 48 36 pm" src="https://cloud.githubusercontent.com/assets/730388/15053412/8911fbbc-12d0-11e6-8233-974a1031b276.png">
