### ISSUE TITLE
Ingest latest data

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#480]
waiting on latest and greatest OV data. Export initiated 11:45am 3/15

**Done when** ingest has run to completion on machine pointed at by "demo.openvault.wgbh-mla.org"

**Comment by Muraszko** [comment]
@afred As of 8:00am 3/16 it's a little over halfway done exporting PBCore records.

**Comment by Muraszko** [comment]
@afred As of 3:00pm 3/16 it's exported 30,000 records of 42,529.  Hopefully I will have the complete PBCore zip for you tomorrow morning.

**Comment by Muraszko** [comment]
@afred As of 6:00am 3/17 it's done 37,686 of 42,529.

**Comment by Muraszko** [comment]
@afred Finished at 6:12om 3/17.
See email for One Drive link to the zip file.

**Comment by afred** [comment]
Done
