### ISSUE TITLE
Records for items in Collections or Exhibits

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#490]
This is not necessary for Launch, but if you could do this sometime in the future, that would be great.

I overlooked an important element in the redesign, which is the graphic on metadata records for items in exhibits and collections. AAPB has this on exhibits: http://americanarchive.org/catalog/cpb-aacip_15-cc0tq5rf2m

Design didn't create this for Open Vault since they considered it an enhancement instead of a redesign of the old features.

I don't think we need Design to create a graphic for us. I propose using a button with background color #FFD679 and font color #063673, similar to the buttons on the homepage. The button width would span the size of the grey box that contains the player in the record. The button could appear just below the grey box. The button would use the same language as AAPB's exhibit referrer graphic. 

Is this possible?

**Comment by mccalluc** [comment]
So I'll put the back-links in, but I don't think it needs to be nearly as prominent as what you propose. This is different from AAPB in that
- Most of the items we have digitized here belong to one or another collection or exhibit: it's not a special case that needs to be highlighted as on AAPB.
- Most of our collections / exhibits are based around series, so the series link already provides a way of reaching related items, while on AAPB there is often no other link between items besides the collection.

So I'll do a first draft which is understated, and we can go from there.

**Comment by mccalluc** [comment]
Technical difficulties: We don't actually have any connection in the data between the url-path-name for a collection/exhibit, and the string in the XML. 

Proposed solution: change the directory names to match the strings in the database, and add to the redirect list for backward compatibility.

**Comment by mccalluc** [comment]
Link backs to collections and exhibits are deployed.
