### ISSUE TITLE
Add CNAME  for hosted wordpress blog

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#492]
**Done when** blog.openvault.wgbh.org points to wgbhopenvault.wordpress.com.

Per email from Casey

> Hi everyone,
> 
> Mike and I spoke this morning, and we decided to create a new Wordpress (hosted) instance like we do for our other blogs (AAPB, AAPB NDSR, and NDSR program). I had attempted to update the look and feel of the current blog, but most of it was coded in CSS and it was not easy to update.
> 
> The hosted version has more flexibility for non-developers. Check it out: https://wgbhopenvault.wordpress.com/
> 
> Now, we just need to change the DNS records so that it points to blog.openvault.wgbh.org. Can one of you help me with this?
> 
> Mike, are you planning to draft a blog post announcing the relaunch, or would you like me to do that? I'd be happy to.
> 
> best,
> Casey

**Comment by afred** [comment]
Ticket filed with IT end user support. Incident # 54694. I would link to it, but I don't think the support desk web app allows it.

**Comment by afred** [comment]
Ryan Groth responded, with this:
> You will need to add that domain to your wordpress site config, I have changed the internal DNS record (for inside GBH) - I didn't want to leave you with a broken site to the world, so have not yet modified the external DNS. Update the wordpress settings and update the ticket and we'll change the external DNS.
> 
> Thanks
> Ryan

Which is a good catch! Thanks to Ryan for not letting me break the blog :smile:

@caseyedavis12 or @Muraszko, one of you need to follow [these instructions](https://en.support.wordpress.com/map-existing-domain/). Unfortunately, it looks like it's going to cost $13/year.

**Comment by caseyedavis12** [comment]
@afred: this is already paid. I will change it now.

**Comment by afred** [comment]
Sweet. @caseyedavis12 can you ping ryan_groth@wgbh.org when it's done, and then close the ticket when he's done on his end?

**Comment by caseyedavis12** [comment]
@afred: I just tried to map wgbhopenvault.wordpress.com to blog.openvault.wgbh.org, and I received the message:


Sorry but blog.openvault.wgbh.org has not been registered yet therefore cannot be mapped.


Is this what I was supposed to map to? I can ask Ryan if you don't know.

**Comment by afred** [comment]
Yes, the idea is to map `blog.openvault.wgbh.org` to the website. I don't know what kind of check WP is making to determine that it hasn't been registered yet. Yeah, I guess ask Ryan.. or do some Googling.. that's what I would have to do.

**Comment by caseyedavis12** [comment]
The blog is working! blog.openvault.wgbh.org.


Close #492
