### ISSUE TITLE
Make carousel shorter on md/sm

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#497]
Images delivered weren't what I was expecting, but we can deal with it. Also figure out what to do with side-scroll arrows overlapping title.

**Comment by caseyedavis12** [comment]
@mccalluc: that was the size that design recommended last week
________________________________

**Comment by mccalluc** [comment]
#469
> choose images such that they can be cropped from the top without harm being done

It doesn't matter, I can work with this.
