### ISSUE TITLE
Materials-Used DB zip is broken

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#498]
on /media-production-organizational-tools the zip of MATUSED is just broken. @caseyedavis12 / @Muraszko ?

**Comment by Muraszko** [comment]
@mccalluc @caseyedavis12 
Here, this one should work:
[MatsUsed.fp7.zip](https://github.com/WGBH/openvault3/files/177669/MatsUsed.fp7.zip)
Note the filename is different than the one it's currently pointing to.

**Comment by caseyedavis12** [comment]
@muraszko @mccalluc: I deleted the MatsUsed database from S3, renamed the one Mike just sent and posted it to S3. It should work now.

**Comment by mccalluc** [comment]
Works. Thanks.
