### ISSUE TITLE
Browse by Series

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#5]
As a user on the homepage, I see a button that says "WGBH Series." When a user clicks on this button, it takes the user to a page listing all WGBH series alphabetically, with one page per letter of the alphabet. See: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553424/OpenVault_final%20comps_v32.jpg

 When a user clicks on one of the series, the user is taken to a search results page for all records in that series.

**Comment by mccalluc** [comment]
This is in good shape, or will be with #61.
