### ISSUE TITLE
Content for contact-us page

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#50]
Someone who will be monitoring it needs to create a contact-us google form, and link to it from override/contact-us.md.

(Also fill in other contact modes on that page if you feel like it.)

**Comment by caseyedavis12** [comment]
@mccalluc: do we need a Google form? Can we just use text and provide an email address? Here is sample text for review @Muraszko: 

We would love to hear from you! If you have general questions or comments about the website and collection, want to share information on the stories you find in the collection, or would like to support the archive being a digitization sponsor, you can reach us at archive_requests@wgbh.org or by mail.

Mailing Address:
Karen Cariani
WGBH Media Library and Archives
WGBH Educational Foundation
One Guest Street
Boston, MA 02135

**Comment by mccalluc** [comment]
That's fine by me: You should be able to edit the text in contact-us.md, so make it whatever you want. I don't need to be involved.

**Comment by caseyedavis12** [comment]
@mccalluc: done.

**Comment by mccalluc** [comment]
fixed linebreaks in #57.

**Comment by Muraszko** [comment]
@caseyedavis12 @mccalluc 
Please use the Open Vault email
openvault@wgbh.org

And change the mailing address name to Open Vault rather than Karen.
Thanks!
