### ISSUE TITLE
Whitney font on openvault.wgbh.org

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#508]
Make sure that the font referrer check is turned off for openvault.wgbh.org

**Comment by afred** [comment]
Email sent to Tim Kinnel.. the typography.com gatekeeper.

**Comment by mccalluc** [comment]
I'm not on the email chain, but when I changed my /etc/hosts so that my local server would spoof that name, fonts worked, so I believe they'll work on the real thing. Closing.

**Comment by afred** [comment]
Yay. Did not receive any confirm in my inbox (will double check), but I guess it has happened.
