### ISSUE TITLE
let images be viewed at full size?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#509]
Right now, images are only being shown at the size of a video, which is usually much less than their native resolution. There will (usually) be nothing over on the right, so there's certainly space.

Proposal: for all image records, try something like max-width: 100%: if the image isn't actually that large, we don't want to stretch it and see pixelation, but we want to use the real estate available, up to that point.

**Comment by caseyedavis12** [comment]
@mccalluc: +1
