### ISSUE TITLE
From The Vault collection records not populating

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#518]
On the From the Vault collection, the records are not populating.

The md has the tag: ```[](http://localhost:3000/catalog?f[special_collection_tags][]=from_the_vault)```

And a record that should be in the collection ```http://demo.openvault.wgbh-mla.org/catalog/V_0669B2FE8ADC4F80A8D89CB58D02BBC0 ``` has the annotation in the PBCore: 
```<pbcoreAnnotation annotationType="Special Collection">from_the_vault</pbcoreAnnotation>```

**Comment by mccalluc** [comment]
Figured it out: We have both special_collections / "Special Collection" and special_collection_tags / "Special Collection Tag". For the other collections we've used special_collections_tags as the basis of the query, and I'd prefer to keep it that way for consistency... Maybe you'll want multiple tabs under *From The Vault* at some point?

@Muraszko : could you add the other annotation to this record? I'll assign this bug to you.

For myself, I'll add more validation to make sure if we have one of these annotations, we have the other.

(This isn't the only way it could be done, but it seems the most consistent to me. Let me know if there are objections.)

**Comment by mccalluc** [comment]
(Spawned #521 for improved validation.)

**Comment by Muraszko** [comment]
Updated and ingested.
