### ISSUE TITLE
Update OAI-PMH feed for New OpenVault

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#52]
We need to make sure that the new Open Vault record pages that have digital objects can be harvested by Digital Commonwealth. This is important for the MVP.

**Comment by caseyedavis12** [comment]
@mccalluc: I am fine with this being post-launch as long as it is implemented within 2-3 weeks after launch.

**Comment by mccalluc** [comment]
@afred: there were more conflicts before, but even after a `bundle update` I get this error:
```
$ bundle update
...
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.1.2)

    blacklight_oai_provider was resolved to 0.0.1, which depends on
      rails (~> 3.0)
```

Options:
- Go with an older Rails version. (bad)
- Invest time to updating blacklight_oai_provider. (good? but uncertain how big a job.)
- Make our own. (bad)
- Or take a step back: The DPLA seemed actually pretty flexible about how the data gets to them... ie, from some folks it sounds like they get CSVs. Could we just give them the same zip of pbcore that the site ingests? (*Zero development!*)

How do we broach this?

**Comment by Muraszko** [comment]
@mccalluc @afred Please see email I've cc'd you both on from Digital Commonwealth, and follow up with Eben.

**Comment by mccalluc** [comment]
>
While feasible to use a zip file, it would make doing future updates more difficult. The OAI feed is likely more sustainable on our end.
>
Would the zip file be just OpenVault items, or would there be other content mixed in? Would there be file-only records that we'd have to filter out?
>
What's the general timeline for getting an OAI feed up, with links that point to items on the new OpenVault site? (Don't need specifics, and not trying to add any pressure, just wondering for the sake of managing our own harvesting timelines here at the BPL.)

I should just try again tomorrow... there's the chance gem have been updated and it'll just work this time.

**Comment by mccalluc** [comment]
same error. alas. Going to make just `ListRecords`; shouldn't be hard.

**Comment by afred** [comment]
:+1: thanks.

I'll bet that if you peek at the gem, it's probably not doing much more than that anyway - maybe with a little extra blacklight magic (black magic?)
