### ISSUE TITLE
Shut down EC2 test instances

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#529]
@mccalluc @afred 
Now we've moved the server to openvault.wgbh-mla.org, can we shut down the ov-qa1.wgbh-mla-test.org instances on Amazon?

**Comment by afred** [comment]
:+1: from me. @mccalluc confirm there's nothing there we need?

**Comment by mccalluc** [comment]
No, and I've requested the deletion of these, and a number of others that were hanging around.
