### ISSUE TITLE
New Open Vault can be redeployed by non-developers

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#53]
The new Open Vault can be redeployed by non-developers, like the new Stock Sales website allows.

**Comment by mccalluc** [comment]
@afred: ETA on the EC2 instance building machinery?

**Comment by afred** [comment]
After working through the ansible stuff, i'm rethinking the idea of triggering a full rebuild and ELB swap for every deploy.

Full rebuild and swap is a process that needs to be solid, but it's time consuming and introduces a lot of moving parts that really aren't necessary for just getting the latest code in place. Particularly, there is a lot of `yum install` and `gem install` going on, which introduce external dependencies.

I think a user-facing script that wraps a Capistrano deployment would be much faster, and have a lower probability of failure.

**Comment by afred** [comment]
@caseyedavis12 ok to take this out of the "launch" milestone?

**Comment by caseyedavis12** [comment]
@afred: Yes, understanding that this is a still a goal to accomplish beyond the end of March launch date.

**Comment by Muraszko** [comment]
Tested and working from following README.

**Comment by afred** [comment]
the README instructions fall quite a ways short of a single button that you can click from a UI, like the Stock Sales site has.

But I'm fine with closing this if others are.

**Comment by mccalluc** [comment]
I'm ok with this.
