### ISSUE TITLE
OAI feed should only be those available on-line

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#533]
http://openvault.wgbh.org/catalog?f[access][]=Available+Online.

**Comment by mccalluc** [comment]
or not, because that would include AAPB as well. Asked Eben if they can filter on their side.

**Comment by Muraszko** [comment]
Could you use the annotation "Digitized" because that value is only for Open Vault available online programs?

**Comment by mccalluc** [comment]
We could, except that it's not something we index right now, but actually adding the filter that only goes partway there would be a plus, because it would decrease the number of items they need to download...
