### ISSUE TITLE
Discuss: Images on collection grid pages load noticeably slow

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#539]
The images on collection page grids are loading rather slowly for me.

[Example](https://drive.google.com/file/d/0B4tUPzNHQTdkQVZWZjFIR29uTGM/view?usp=sharing)

Is this because I'm currently in California?
~~Or because I have my VPN on?~~ <== nope

**Comment by mccalluc** [comment]
@afred: Just discovered Chrome's fake throttling: Dev tools; network tab; and the right-most of the options below that. 

- All the images (at least on the top of the page) seem to be loading simultaneously, so the CNAMEs hack is not something to pursue... actually we want to go in the opposite direction.
- so I think we need to just get better image quality in fewer bytes
   - more jpeg compression?
   - png? Many of these images have large areas of solid color and a small palette, so PNG shouldn't be precluded.
- .... or fewer images? All the images are loading simultaneously... but the subjective sense of speed might be improved if we loaded the first 6, and only then loaded the second 6: The second batch will usually be off-screen, so we can afford to wait before starting them.

**Comment by mccalluc** [comment]
Oh. They are already PNGs. They almost certainly could be made smaller, either compressing the PNG, or using JPEG, which would have been the more obvious choice to begin with.

@caseyedavis12 : I guess you've collected most of these images? FYI, PNG is a loss-less format, and wouldn't be my first choice for photographs.

**Comment by mccalluc** [comment]
Just taking imagemagick's default compression level, we're saving a whole lot. I'll move these files up to S3 and make a PR with the MD changes.

```
 104 scholar_exhibits/advocates/advocates_554x340.jpg
1832 scholar_exhibits/advocates/advocates_554x340.png

 104 scholar_exhibits/art_of_asian_cooking/art_of_asian_cooking_554x340.jpg
1744 scholar_exhibits/art_of_asian_cooking/art_of_asian_cooking_554x340.png

  80 scholar_exhibits/bibring/bibring_554x340.jpg
1512 scholar_exhibits/bibring/bibring_554x340.png

  64 scholar_exhibits/boring_and_sachs/boring_and_sachs_554x340.jpg
1184 scholar_exhibits/boring_and_sachs/boring_and_sachs_554x340.png

 128 scholar_exhibits/boston_civil_rights/boston_civil_rights_554x340.jpg
 512 scholar_exhibits/boston_civil_rights/boston_civil_rights_554x340.png

 112 scholar_exhibits/eric_jackson/eric_jackson_554x340.jpg
 696 scholar_exhibits/eric_jackson/eric_jackson_554x340.png

  72 scholar_exhibits/fenway_park/fenway_park_554x340.jpg
 464 scholar_exhibits/fenway_park/fenway_park_554x340.png

  48 scholar_exhibits/james_baldwin/james_baldwin_554x340.jpg
 368 scholar_exhibits/james_baldwin/james_baldwin_554x340.png

 128 scholar_exhibits/julia_child/julia_child_554x340.jpg
 736 scholar_exhibits/julia_child/julia_child_554x340.png

  72 scholar_exhibits/leary_and_jobs/leary_and_jobs_554x340.jpg
 408 scholar_exhibits/leary_and_jobs/leary_and_jobs_554x340.png

 120 scholar_exhibits/needlework/needlework_554x340.jpg
1840 scholar_exhibits/needlework/needlework_554x340.png

  64 scholar_exhibits/new_critical_television/new_critical_television_554x340.jpg
1376 scholar_exhibits/new_critical_television/new_critical_television_554x340.png

  80 scholar_exhibits/nine_poets/nine_poets_554x340.jpg
 376 scholar_exhibits/nine_poets/nine_poets_554x340.png

 104 scholar_exhibits/pan-african_liberation/pan-african_liberation_554x340.jpg
 616 scholar_exhibits/pan-african_liberation/pan-african_liberation_554x340.png

 120 scholar_exhibits/showing_status/showing_status_554x340.jpg
 592 scholar_exhibits/showing_status/showing_status_554x340.png

  80 scholar_exhibits/tech-nostalgia/tech-nostalgia_554x340.jpg
 504 scholar_exhibits/tech-nostalgia/tech-nostalgia_554x340.png

  80 scholar_exhibits/television_violence/television_violence_554x340.jpg
1280 scholar_exhibits/television_violence/television_violence_554x340.png

 104 scholar_exhibits/zoom/zoom_554x340.jpg
1888 scholar_exhibits/zoom/zoom_554x340.png

  88 special_collections/aapb/aapb.jpg
 288 special_collections/aapb/aapb.png

 104 special_collections/advocates/advocates.jpg
 464 special_collections/advocates/advocates.png

 128 special_collections/from_the_vault/from_the_vault.jpg
 680 special_collections/from_the_vault/from_the_vault.png

  96 special_collections/march_washington/march_washington.jpg
 336 special_collections/march_washington/march_washington.png

  72 special_collections/ntw/ntw.jpg
 224 special_collections/ntw/ntw.png

  64 special_collections/press_people/press_people.jpg
 304 special_collections/press_people/press_people.png

 208 special_collections/rock_roll/rock_roll.jpg
 752 special_collections/rock_roll/rock_roll.png

 136 special_collections/say_brother/say_brother.jpg
 752 special_collections/say_brother/say_brother.png

  88 special_collections/stock_sales/stock_sales.jpg
 408 special_collections/stock_sales/stock_sales.png

 104 special_collections/tocn/tocn.jpg
 352 special_collections/tocn/tocn.png

 104 special_collections/vietnam/vietnam.jpg
 496 special_collections/vietnam/vietnam.png

  64 special_collections/war_peace/war_peace.jpg
 264 special_collections/war_peace/war_peace.png
```

**Comment by caseyedavis12** [comment]
@mccalluc: Thanks

**Comment by Muraszko** [comment]
@mccalluc @afred Were either of you able to reproduce this?  

Are all these png -> jpg changes more a result of best practices in presenting images or a reaction to this issue?

If it's following best practices, cool.  I'll make sure to put somewhere in the documentation when creating images for exhibit, collection, carousel, etc, to use jpg.

**Comment by mccalluc** [comment]
@Muraszko 
- Reproduction: see my first comment in this thread
- This issue brought it to my attention, but yes, jpg is usually the best practice for photos on the web. PNG should be thought of as a replacement for GIF.

**Comment by Muraszko** [comment]
@mccalluc 
Got it, thanks.  Then I say go for it and I'll be sure to include in the documentation to use jpg in the future.

**Comment by mccalluc** [comment]
png -> jpg fixed it. closing.

**Comment by afred** [comment]
👏
