### ISSUE TITLE
lots of 500s should be 404s

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#542]

**Comment by mccalluc** [comment]
huh: so on production [this](http://openvault.wgbh.org/asdf) is a 500, but locally I get: 404, routing error. This is the code:
```
ActionController::RoutingError.new('404')
```
Does that get handled differently, depending on context?

**Comment by afred** [comment]
@mccalluc Interesting. I would have expected it to be the other way around.

Are you sure that production is reaching that line with the `RoutingError.new('404')`?

**Comment by mccalluc** [comment]
The example is now a 404:
```
$ curl -I http://openvault.wgbh.org/asdf
HTTP/1.1 404 Not Found
```

Closing.
