### ISSUE TITLE
Discrepancies in color spec

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#55]
The spec color values do not match the colors actually used in the screen shots. Just two examples
- darkest blue:
```
spec value: #06 36 73 // High blue channel: close to a pure blue
comp value: #19 35 58 // Low blue, more red: more of a navy
```
- yellow:
```
spec value: #6D 6E 71 // All channels nearly equal: this is a grey
comp value: #F4 BA 54 // High R+G, some B. Rich yellow, a bit mustard.
```

Right now in the branch I have out, I'm using the spec values, except for the yellow. I really don't care about the precise shades, but other folks do, and there are contradictory instructions right now. I don't need to be involved in this: edit colors.css.scss as you see fit.

**Comment by caseyedavis12** [comment]
@mccalluc: I am moving this to pre-launch, but I changed the color specs in the css document and I believe that pull request was already merged, so I don't think there are any action items for you.

**Comment by mccalluc** [comment]
Casey's commit: 5641dcb08b4. Want to remove TODOs since it's done, and then close this.

**Comment by mccalluc** [comment]
PR is in. A little curious what should be our practice in the future: Are design's hex values any good, or should we always just use the color dropper?
