### ISSUE TITLE
Missing Transcript

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault3#569]
The transcript for [this record](http://openvault.wgbh.org/catalog/V_48DC3F60A016451F98A1A774BAD56F44) isn't appearing on the page.
I've checked that the transcript xml file is on S3 where it should be, named what it should be, and it's not a 0kb file or anything like that.

@mccalluc Could you please look into this?

**Comment by mccalluc** [comment]
I'm reproducing the problem locally, and I'm looking into it. First guess is that there's an error in the transcript, and we put up our one-size-fits-all error page.

**Comment by Muraszko** [comment]
I tried to copy the transcript from S3, but I don't think permissions allow for that.  I tried in the CLI and web interface.  I could check the xml if I can get a copy.

**Comment by mccalluc** [comment]
That part is working... it's something to do with the processing downstream.

**Comment by mccalluc** [comment]
This works:
```ruby
Nokogiri::XML(ugly_xml) { |config| }
```
but this fails:
```ruby
Nokogiri::XML(ugly_xml) { |config| config.options = Nokogiri::XML::ParseOptions::NOBLANKS }
```

What does the `ugly_xml` look like? It's the output of the XSLT, and it contains:
```xml
<div class="incident" id="__incident0" data-timecodebegin="00:00:00" data-timecodeend="00:00:02.523">
                        5/7/1981<br> SR 2410<br> Tran Van Don<br> Sound roll 1. Marker. 573. Clapstick.
                    </div>
```
which could certainly cause problems. Our XSL is set to produce HTML, not XML. arg.

(This code is fairly new: I wanted to pretty print the html, and the NOBLANKS is the way to do that with nokogiri.
