### ISSUE TITLE
Discuss: should ever change the "Access" facet if the user has selected it?

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#572]
**Story**
As a User
When I am on the search page,
And when I have performed a search,
And when I have selected "Access: All Records" from the facet menu,
And when I do another search,
I do not have to re-select "Access: All Records" from the facet menu - it is still selected based on my previous actions.

**Current behavior:** user has to re-select "Access: All Records" after they have already selected it once.

@mccalluc I think maybe just adding a conditional around [the line that adds the default value for the "Access" facet](https://github.com/WGBH/openvault3/blob/86771c9f738c0e914082a4e66466fe07b29dd4fb/app/controllers/catalog_controller.rb#L170) may be enough.

**Comment by mccalluc** [comment]
@afred: More generally, should all the current facets be preserved when you enter a new search, or is Access special?

**Comment by afred** [comment]
👍 for all facets.

fwiw, I think this is a regression from default Blacklight behavior (maybe from overwriting the `#index` method?) AAPB keeps the selected facets for subsequent searches, as does Boston Local TV News.

Before rolling our own solution, maybe take a peek into Blacklight and see if there's a way to easily resurface the default behavior.
