### ISSUE TITLE
Figure out referer hostname checking on S3

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#58]
Right now, the content on S3 could be referenced by any site, and we'd be paying for the downloads. We need to figure out hostname checking on S3.

**Comment by afred** [comment]
here's a [reference on putting conditionals in bucket policies, specifically for checking http referrer](http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-4)
