### ISSUE TITLE
Add DONATE to header

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#596]
Related to #594, add DONATE to OpenVault website header. @mccalluc: is there a way to make DONATE highlighted with a different color like on wgbh.org's header http://www.wgbh.org/?

**Comment by afred** [comment]
@caseyedavis12 yes. The donate button is not supplied by Kimbia. It's under our control. We can also style them differently in the header and footer if so desired.

**Comment by caseyedavis12** [comment]
@afred: Great, I think it would be good to style the button differently than the other buttons to make it stand out on the page, like wgbh.org has done.

**Comment by afred** [comment]
Agree.. i think we should go for "unmissable, but unobtrusive", I think the wgbh.org button does a good job of getting that balance

**Comment by caseyedavis12** [comment]
@mccalluc: Can you work on creating a styled button in the header that links to the Donate page?
