### ISSUE TITLE
Open Vault Record Page: Displayed Metadata

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#6]
The following metadata fields should appear in this order on a record page if the metadata exists.
See style comps for design layout: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553431/OpenVault_final%20comps_v39.jpg

As a header above the player/thumbnail:
[All titles concatenated from most general to most specific and separated by semi-colons]
Date:

Below the player/thumbnail:
Series: [value hyperlinked]
Program: [value hyperlinked]
Program Number:
Title:
Series Description: [with Series Date Release appended at the end of the description]
Program Description:
Description:
Duration:
Asset Type:
Media Type:
Subjects: [values hyperlinked]
Location: [values hyperlinked]
Series Genre: [values hyperlinked]
Series Topic: [values hyperlinked]
Creator: [Creator Name, Role]
Contributor: [Contributor Name, Role]
Publication Information: [Publisher Name]
Rights Summary: [Rights Holder; Rights Credit]

**[values hyperlinked] should take the user to a search result for other records with that value.

**Comment by mccalluc** [comment]
@caseyedavis12 : 
- Between you and Mike, there's a clear notion of "Open Vault Title"? Do we actually mean something like "Item Title"?
- There is no item level description?
- The only date metadata we display is the series release date?

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, the Open Vault Title is an item title for the well-cataloged records. 
I am meeting with Mike at 11am to confirm the fields in the metadata and I will provide a crosswalk from PBCore to displayed field name. Your other two questions will be answered in that crosswalk.

**Comment by caseyedavis12** [comment]
@mccalluc: See #38 for information about PBCore fields and how each will be displayed. 

I updated this ticket, which is primarily to recommend order of displayed fields, but now each field listed on this ticket is named according to the decisions made yesterday. 

To answer your questions from yesterday, there is sometimes an item level description in pbcoreDescription descriptionType="Asset Description," which should be labeled as "Description"

There is only one date field: pbcoreAssetDate which should be displayed as Date.

**Comment by mccalluc** [comment]
@caseyedavis12 : 
> Publication Information: [Publisher Name, Role]
In the spreadsheet publisher doesn't have role. Please correct one or the other.

**Comment by caseyedavis12** [comment]
@mccalluc: Fixed on this issue. publisherRole is not in the XML.

**Comment by mccalluc** [comment]
@caseyedavis12 : Comparing this to what's currently implemented:
- One of the mockups had the description above the player, so that's what I've done, rather than placing it in the longer list here.
- Just realized that you've got all the last items as links:
```
Creator: [Creator Name, Role]
Contributor: [Contributor Name, Role]
Publication Information: [Publisher Name]
Rights Summary: [Rights Holder; Rights Credit]
```
  - Do you really want a link on Rights? What query would it do?
  - For the rest, what search should they do? My thinking right now would be to make a phrase search on all text fields. ie, given `John Doe, scriptwriter` clicking on the link would find any record with "John Doe" anywhere... put you might want a more precise search?

**Comment by caseyedavis12** [comment]
@mccalluc: The values of rights are controlled. One controlled value, for example, is Public Domain. I think it would be good to have those values linked so that a user can click on "Public Domain" and then see a search results for all items with that value.

For the rest, what search should they do? My thinking right now would be to make a phrase search on all text fields. ie, given John Doe, scriptwriter clicking on the link would find any record with "John Doe" anywhere... GOOD IDEA.

**Comment by mccalluc** [comment]
New bugs filed for the remaining items. Closing this.
