### ISSUE TITLE
Stylesheet for Donate page tabs

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#602]
Nick has asked if we could create a simple stylesheet to make the tabs more clear and apparent on the Donate page. Perhaps make the tabs a different color, similar to the WBGH donate page: http://www.wgbh.org/support/donatebutton.cfm

His concern is that someone might accidentally make a monthly donation because when they are trying to make a one-time donation.

I could also add header text to each section below the tab if creating a stylesheet is too time-consuming.

This is what the donate page currently looks like: See here: http://demo.openvault.wgbh-mla.org/donate

**Comment by mccalluc** [comment]
could revisit, but with the it's in an acceptable state.
