### ISSUE TITLE
Fix transcript sync buttons

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#607]
**Done when**
  * arrow is centered inside the "button", vertically and horizontally
  * right-margin after the button

**Comment by mccalluc** [comment]
I don't have a handle on the vertical centering. I only see it on FF, on the demo site. From localhost, or from either host under chrome, it looks fine. I've copied down the CSS that gets applied and done a diff, and there is no diff. Best guess is that FF is caching something that is causing the difference?
