### ISSUE TITLE
Add link in "No Results" page that links to same query with "All Records" facet selected.

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#612]
**Done when** the page for an empty query has a link to the same query with the "All Records" option turned on, if it was not on already

**Comment by mccalluc** [comment]
I had interpreted this as something we wanted on all results pages, not sure empty query ones?

**Comment by afred** [comment]
oh, i must have missed that. Whatever @caseyedavis12 said.

**Comment by Muraszko** [comment]
Slight display bug mentioned in #616
