### ISSUE TITLE
Kimbia flakey

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#619]
The Kimbia JS is either failing outright, or taking 30 seconds to come back.
```
[openvault3]$ URL='https://widgets.kimbia.com/js/api_v2.js?method=getFormList&random=0.4034220497909625&argument=.kba%3AH4sIAAAAAAAAA6tWykxRslIyNnJ08wo1VtJRyk0tLk5Mz8xLDyjKT8vMSVWyyivNydFRSkwpy09OLEn1TIGJFBSlAhXkIARKUhNzQ%2FK98jPzYGK1AAnEQ25fAAAA&callback=jQuery172020910094950292835_1462301340480&.kba:H4sIAAAAAAAAA6tWykxRslIyNnJ08wo1VtJRyk0tLk5Mz8xLDyjKT8vMSVWyyivNydFRSkwpy09OLEn1TIGJFBSlAhXkIARKUhNzQ/K98jPzYGK1AAnEQ25fAAAA&_=1462301340501' 

[openvault3]$ time ( curl $URL )
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
curl: (56) SSLRead() return error -9806
real	0m4.045s
user	0m0.032s
sys	0m0.013s

[openvault3]$ time ( curl $URL )
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
curl: (56) SSLRead() return error -9806
real	0m0.648s
user	0m0.029s
sys	0m0.010s

[openvault3]$ time ( curl $URL )
/* API host: app3_platform1 */
(function(){
...
})();
real	0m35.118s
user	0m0.032s
sys	0m0.014s
```

And now I'm getting java errors?

@Muraszko / @caseyedavis12 :
1. Just be aware that widget might not be loading for reasons outside my control
2. If we're paying any money to Kimbia, we should make sure we're getting the service we are due. Is there an SLA?

**Comment by Muraszko** [comment]
@mccalluc I think it's a Kimbia issue, [see WGBH's donate page](http://www.wgbh.org/support/makeagift.cfm)

**Comment by Muraszko** [comment]
Yikes
![screen shot 2016-05-03 at 3 37 23 pm](https://cloud.githubusercontent.com/assets/6650285/14995848/f4a37e2e-1144-11e6-925e-279d807d981d.jpg)

**Comment by mccalluc** [comment]
Ok, I'll close this, but if you can think of anything actionable, feel free to reopen.

**Comment by caseyedavis12** [comment]
@mccalluc @muraszko - looks like it's back up and running. I hope that's not a usual occurrence...

________________________________
