### ISSUE TITLE
"License Clip" button?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#633]
@Muraszko : Talking with the Stock Sales folks, it came up that visitors to OV might not know how to move forward with licensing. Proposal is to add a button like this on every record:
<img width="424" alt="screen shot 2016-06-28 at 3 32 36 pm" src="https://cloud.githubusercontent.com/assets/730388/16429713/3e2772e4-3d46-11e6-86de-d04b8a10d6e2.png">
Thoughts?
- They will provide copy that will appear in the dialog. If you have thoughts on what it should say, that would be good to know.
- Are you the product owner of OV? Who would OK this?
- Is every record ok, or should there be some filter?

**Comment by mccalluc** [comment]
@caseyedavis12 : What are your thoughts on this proposal?
cc: @AlisonCSmith

**Comment by caseyedavis12** [comment]
@mccalluc: I think it's a great idea. Will @alisoncsmith provide copy for the pop-up window?


________________________________

**Comment by AlisonCSmith** [comment]
she definitely will!
:)
Alison

Be sure to visit our website: www.wgbhstocksales.org
WGBH: The Power of Public Media
