### ISSUE TITLE
For discussion: Rethinking OV search results layout

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#646]
During NCAM's accessibility review of AAPB website, It was recommended that thumbnails be hidden from screenreader on search results. If we remove images from search results on Open Vault, all the information that is left is the title. 

For discussion: is this enough information to convey on search results? Should we rethink having a list view with more descriptive information on search results such as date, online availability status and media type, instead of the grid view?

**Comment by jasoncorum** [comment]
*Done When* we use 100 characters of asset level descriptions in hidden text for screenreaders. If no description is available, do not use any description. Just leave title.

**Comment by jasoncorum** [comment]
While this worked great for search results, not so much for the Exhibits grid. Need to refactor.
