### ISSUE TITLE
Transcript window should have option to be hidden 

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#650]
There should be an option to hide the transcript reader.

**Comment by jasoncorum** [comment]
@caseyedavis12. Screenshots below. Let me know if you'd like to tweak anything! If not, I can submit a PR.

Open (default open)
![screen shot 2017-01-05 at 11 45 43 am](https://cloud.githubusercontent.com/assets/3814190/21688909/9b0c3d5a-d33c-11e6-90d9-eb7df1ec80fc.png)

Closed
![screen shot 2017-01-05 at 11 46 52 am](https://cloud.githubusercontent.com/assets/3814190/21688935/b521e0c8-d33c-11e6-8168-7ab26bd8188a.png)

**Comment by caseyedavis12** [comment]
@jasoncorum this looks great to me!

**Comment by afred** [comment]
What's the bit about...

> Translates to br in html: self closing tags can be parse problems.

...?
