### ISSUE TITLE
Malcolm X interview not appearing online

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#681]
This Malcolm X interview from Say Brother is featured in the "From the Vault" Special Collection, and on the AAPB website it appears as "available online at WGBH." But there is no proxy file associated with this asset on Open Vault, and there is no "Digitized" annotation that indicates that it should be online. Should this asset have a proxy file?

http://openvault.wgbh.org/catalog/V_7211FEA594634BC9B984B4AFA493D446

@Muraszko-wgbh

**Comment by Muraszko-wgbh** [comment]
@caseyedavis12 That link to Malcolm X is the entire show.  Here is the record for the interview:
http://openvault.wgbh.org/catalog/V_FE25740F38E943A0986F93AD4A03E425

Must have been a mistake in the AAPB annotation?  Is the AAPB link the whole show or the clip?

**Comment by caseyedavis12** [comment]
@muraszko-wgbh: the AAPB link is to the Say Brother Malcolm X episode: http://americanarchive.org/catalog/cpb-aacip_15-r20rr1pv84

**Comment by Muraszko-wgbh** [comment]
So was it digitized, and I assume LoC or WGBH viewable only.  You can probably just remove the link to Open Vault then.

**Comment by caseyedavis12** [comment]
@muraszko-wgbh: Since the Say Brother Malcolm X episode record on AAPB has a UOI ID, I think this program was downloaded from Artesia as part of the "born digital" phase. Since this record was part of the Pan African Liberation scholar exhibit and From the Vault, are we sure that it was never supposed to be made available online?


Both the Malcolm X Interview from Negro and the American Promise and the Say Brother Malcolm X episode are included in the From the Vault collection. I'm just doing a sampling and haven't found any other assets in the From the Vault collection that do not have media associated with the record.

**Comment by caseyedavis12** [comment]
@sroosa: can you remove the Outside URL annotation from this record: http://americanarchive.org/catalog/cpb-aacip_15-r20rr1pv84


Also, please change the Level of User Access annotation to On Location, and then please reindex.

**Comment by sroosa** [comment]
Done when record appears on AAPB without link to Open Vault and metadata reflects that it is available to view On Location only. 

Done
