### ISSUE TITLE
Static Pages to Create/Edit

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#7]
- [x] About Us
- [ ] Funding
- [ ] Projects
- [x] Contact Us
- [x] Help
- [x] Credits
- [x] Visiting the Archives

**Comment by Muraszko** [comment]
Also, Media Production Organizational Tools page

**Comment by Muraszko** [comment]
sent email with content text and images 12/24/2015

**Comment by mccalluc** [comment]
- [ ] about -> /pdf/WGBHMLAAssessment.pdf
- [ ] media-production-organizational-tools -> * (all links are dead)
- [ ] credits (missing logos / out of date)

- @caseyedavis12 : There don't seem to be "funding" or "projects" pages on the old site. If I'm missing it, where is it? If it wasn't there, do we need a new page on the new site?

**Comment by caseyedavis12** [comment]
@mccalluc: I am in the process of editing all of the static pages. The funding a projects pages will be new pages.

________________________________

**Comment by mccalluc** [comment]
@caseyedavis12 : Summarizing the current state:

- about -> /pdf/WGBHMLAAssessment.pdf  
Legal is doing a review.
- credits (missing logos / out of date)  
Pages are in, imgs commented out, pending review
- Funding
- Projects  
Are more pages necessary than what we already have?

**Comment by caseyedavis12** [comment]
@mccalluc: I have a branch open titled "credits-tweaks."


The content of the credits pages have been updated and approved.


 I have received approval from most foundations for logos, and am waiting on approval from two foundations. When we receive approval from the last two foundations, I will remove the comments from the imgs and add the three Mellon reports within the md and on s3.


Then I will issue a PR.


Funding and Projects pages are no longer necessary.


This is not a blocker on making the switch today. Please note that a markdown redeploy will be requested probably next week, once we have received approval from the last two foundations.

**Comment by Muraszko** [comment]
I think these have been resolved, reopen if that is not the case.
