### ISSUE TITLE
How grids should work?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#70]
```xml
<!-- all divs get class="col-md-4 col-sm-6" -->
<div>item 1</div>
<div>item 2</div>
<br class="hidden-md hidden-lg"/>
<div>item 3</div>
<br class="hidden-sm"/>
<div>item 4</div>
<br class="hidden-md hidden-lg"/>
<div>item 5</div>
<div>item 6</div>
<br/>
<!-- and repeat -->
```
(With default of 12 items: Spec does not call for this to be controlled in the UI.)

@afred: Let me know if you have any objections in principle to this approach. I would like to use it on all our grids. Everything else I can think of falls short in some significant way.
- flexbox: spotty browser support.
- table: non-responsive.
- fixed heights: we end up reserving too much room on some rows, and not enough on others.
- client-side injection of brs: AAPB tried to do this and we scrapped it.

**Comment by afred** [comment]
I'd like to take another stab at flexbox before discounting it. It looks like [Bootstrap is moving that way anyway](http://v4-alpha.getbootstrap.com/getting-started/flexbox/).

@Muraszko this touches on another area for evaluating websites: browser support. How broad, and how far back, do we go? I don't think we've ever written anything down.

**Comment by mccalluc** [comment]
$0.02: I felt burned by flexbox: I just don't think the browser support for even slightly out of date browsers is there to make this a good choice. http://caniuse.com/#feat=flexbox (Check the percents in the upper right.)

**Comment by afred** [comment]
right on :+1: to your approach above.

**Comment by afred** [comment]
please try to keep in mind that our minds are likely to change regarding how many items we want to show per row at different break points. Having the ability to quickly change it would be nice.

**Comment by mccalluc** [comment]
keeping open until I make a partial and apply it to collections.

**Comment by mccalluc** [comment]
I would still like to apply this to the collection/exhibit index pages, but #92 is open for that. Closing.
