### ISSUE TITLE
Proxy if-and-only-if Digitized?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#71]
@Muraszko : Just wanted to confirm that my understanding is correct: There will be a proxy if-and-only-if the item is digitized... right?

(This is not currently a facet, ie, there is no option to limit to playable media, like we have on AAPB. @caseyedavis12 : Is this an oversight, or are we expecting folks to navigate in from collections/exhibits, so it won't be such a problem?)

**Comment by Muraszko** [comment]
@mccalluc Correct.  pbcoreAnnotation type="Digitized" and the value should be, "YES".

**Comment by mccalluc** [comment]
@Muraszko: Sounds good. The code is currently like this:
```ruby
  def proxy_srcs
    @proxy_srcs ||= 
      if xpath_boolean('/*/pbcoreAnnotation[@annotationType="Digitized"]')
        extensions.map { |ext| "#{URL_BASE}/asset_proxies/#{id}.#{ext}" }
      else
        []
      end
  end
```
Worth noting that if there is a file on S3, but the digitized flag isn't on, we won't notice. I'm ok with this, but let me know if you'd like the check in that direction, too.

(Will wait to close until feedback from @caseyedavis12.)

**Comment by Muraszko** [comment]
Good to know.  I'm fine with files existing on S3 that the code won't check against.  In our proxy ingest process we get a list of all the files in a particular bucket anyway, so if there is one that doesn't match against the list of database records we should catch it there after ingest.
