### ISSUE TITLE
zcat for ingest, to avoid creating files? or Nokogiri::XML::Reader?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#72]
@foo4thought : One thought on ingest: what if I used `zcat` and then parsed the stream, rather than actually creating all the files? This would sort-of be a poor-man's SAX. This would make it more dependent on the line-formatting, but that's probably ok? We'd also want to be sure that the zipping on your end didn't run into any weird file-count limits. 

Or, if generating the collection isn't a problem you end, Nokogiri::XML::Reader might be worth a look: Not quite as low level as SAX, but it does let you read a document one top-level node at a time, instead of blowing out the memory.

**Comment by foo4thought** [comment]
`zip` is a better option.  e.g., 
`#!/binbash
for xml_item in "$( unzip -l $the_zip_file | grep 'xml$' )";
do this_xml="$( unzip -p $the_zip_file $xml_item )";
# do work here
done





`

**Comment by mccalluc** [comment]
@foo4thought : nifty. (Though I needed `gunzip -l` and `gunzip --stdout` for the last file I received.

But: Will I get pbcoreCollections, or a zip with many files? (last example I have from you is a collection, though I thought we were going the other direction?) I think I can make either approach work, but I don't want to spend time on machinery that might not be used.

**Comment by foo4thought** [comment]
you have a ZIP file with pbcoreDescriptionDocument XML documents on OneDrive

**Comment by mccalluc** [comment]
(Ended up using the ruby zip library to iterate. Close.)
