### ISSUE TITLE
Size and aspect ratio for thumbnails / placeholders?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#75]
@Muraszko : can you clarify what dimensions and aspect ratio our thumbnails should have? And how we should get there from here?

To take a single example:
- https://s3.amazonaws.com/openvault.wgbh.org/catalog/asset_thumbnails/V_5FDB1545443B427888C90E7B15F3783A.jpg
  - 720x486 
  - 360x243 as displayed currently in lg mode
  - ratio: 1.481
- placeholder image supplied by design
  - 363x229
  - 360x227 as displayed
  - ratio: 1.585
(Remember 4/3 = 1.333; 16/9 = 1.777)

Both you and design must have made conscious decisions about how to size your images, so I don't understand how we ended up here.

In the results list we can just use a containing div which hides the overflow, but the splash in the player is less flexible, and we end up with a gap at the top and bottom: (the grey bars at top and bottom)
![screen shot 2016-01-20 at 6 24 18 pm](https://cloud.githubusercontent.com/assets/730388/12466502/18553f2c-bfa3-11e5-93a8-05e3b0cb973e.png)

**Comment by Muraszko** [comment]
@mccalluc Where are you getting the video player size spec?  I don't see it in their comps.

So your unable to resize the thumbnail as it's being displayed inside the player?  Because that's the preferred way to solve this because like the Sales site, the thumbnails for assets are not a standard size.

**Comment by mccalluc** [comment]
@Muraszko : The player size is just something close to what their mockups look like. (There is ambiguity everywhere, and so for the most part I make things up and if it's a horrible decision someone can complain at some point.)

As far as the sales site, no, we are not resizing thumbnails there:
```
<video 
  controls="true" 
  oncontextmenu="return false;" 
  poster="https://d14nxlyhj878kl.cloudfront.net/cifiles/76bd5c7c66254bc1a2dce466b7f741e7/thumbnail.jpg?Policy=..." 
  src="/media/GBH00000011001014" 
  width="100%">
</video>
```

(The posters are supplied by Ci, and they seem to match the video.)

It would probably help to separate out the issues here:
- What should the aspect ratio be on the search results? My guess is that we should match the placeholders they've provided, and hide any overflow.
- Should I just take off the hard-coded height and width on the player on details? The result is smaller than in the mockups...
- How did we seem to end up with thumbnails that have different dimensions than the video.

*Probably best not to worry too much about this until we have a server up that you can look at.*

**Comment by Muraszko** [comment]
**How did we seem to end up with thumbnails that have different dimensions than the video.**
1) We're using legacy thumbnails, so who knows how they were created.
2) Some thumbnails were cropped to look best, so they are typically created from the essence video, not the actual proxy video we provide on the website that is watermarked.

**Comment by caseyedavis12** [comment]
@mccalluc: *What should the aspect ratio be on the search results? My guess is that we should match the placeholders they've provided, and hide any overflow.*
**Agree**

*Should I just take off the hard-coded height and width on the player on details? The result is smaller than in the mockups...*
**I will wait until server is up to look at the options**

**Comment by mccalluc** [comment]
(Changing milestone to launch: We'll look at what we have and decide what the real end goal is.)
