### ISSUE TITLE
Geoblock should be country code, not boolean

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#76]
@foo4thought : Thinking about what the geoblock actually does: As far as I know, it blocks requests from country code "GB" for an handful of interviews from the computer series. Rather than having this as boolean in the xml, I'd really prefer if we could just record the country code which needs to be blocked. This is more transparent and future-proof. Is that doable?

**Comment by foo4thought** [comment]
the expression of that as boolean is a waste; it should be an explicit list of blacklist values or whitelist values, whichever is most efficient and effective.  @Muraszko ?

**Comment by Muraszko** [comment]
I don't care.  If you'd rather me provide the list of open vault ids for those files to geoblock I can and will remove the geoblock.

Would this live in a config file of some kind?

**Comment by mccalluc** [comment]
Sorry to have muddled this. Where the xml currently has
```xml
<pbcoreAnnotation annotationType="Geoblock">YES</pbcoreAnnotation>
```
I'd like to instead have
```xml
<pbcoreAnnotation annotationType="Geoblock">GB</pbcoreAnnotation>
```
We can worry about the representation of multiple countries when we get to that point.

**Comment by Muraszko** [comment]
@mccalluc That's fine.  I will change the Geoblock annotation to GB for those records when I'm able to edit the PBCore in the database.  Thanks.

**Comment by Muraszko** [comment]
@mccalluc Quick note, the latest XML should be:
```
<pbcoreAnnotation annotationType="Geoblock">United Kingdom</pbcoreAnnotation>
```
Do  you still want it expressed as "GB"?

**Comment by mccalluc** [comment]
@Muraszko : I would really prefer the two letter code: It's what our geocoding library returns: If we did names, then we need to maintain a mapping from long names to codes.

**Comment by Muraszko** [comment]
You got it!

**Comment by mccalluc** [comment]
I believe this is fixed, but if it really matters, we should confirm behavior through a remote proxy, but leave that for the QA team.

**Comment by mccalluc** [comment]
Latest test export I got from Kevin:
```
WARN [2016-02-23 12:22:30]: 1 (6.3%) PBCoreIngester::ValidationError: Value validation errors: Unexpected blocked country codes: ["United Kingdom"]
INFO [2016-02-23 12:22:30]: 15 (93.8%) succeeded
```

reopening.

**Comment by Muraszko** [comment]
@mccalluc Yeah, I haven't fixed this yet as well as other element corrections that will be throwing off your errors.

**Comment by mccalluc** [comment]
(Note that we now want three letter codes. Assign to @Muraszko to make clear that this is a data issue.)

**Comment by Muraszko** [comment]
Ingest was successful.
