### ISSUE TITLE
"Digitize on Demand" on record page with mail-to link

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#8]
On a metadata record page for non-digitized video and audio, the user sees a box that says "This item has not been digitized. [Contact us], indicating the Open Vault URL, to request digitization."

When the user clicks on Contact us, an email window opens and is addressed to Mike.

**Comment by Muraszko** [comment]
@caseyedavis12 Actually, you could use the email openvault@wgbh.org.  That gets monitored by multiple people.
Thanks
