### ISSUE TITLE
facets need to be multicolumn

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#80]
ten values and then wrap? Or do something to get even groups?

**Comment by caseyedavis12** [comment]
@mccalluc: What is the maximum number of values for the facets?

**Comment by mccalluc** [comment]
I don't think we should set a maximum, unless for aesthetic reasons you want to set a max. (Up top, those were questions to myself: I feel confident that I can come up with something reasonable right now.)

**Comment by caseyedavis12** [comment]
@mccalluc: I am sure you will come up with something good. The WGBH Forum Network website has a horizontal facet menu which may provide some inspiration: http://forum-network.org/lectures/

**Comment by mccalluc** [comment]
Close in favor of #87.
