### ISSUE TITLE
facet menus should not be expanded on page load, even if selected.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#82]
They'll obscure the content, and be a distraction. Look at OV for an example of how to override this.

**Comment by caseyedavis12** [comment]
@mccalluc: is there a way to communicate to the user above the facets what filters they have applied? See the red text above the facets in this screenshot:
![screen shot 2016-01-22 at 7 37 31 am](https://cloud.githubusercontent.com/assets/5992135/12510890/2774bcec-c0db-11e5-8c7e-7718e3326c24.png)

**Comment by afred** [comment]
@mccalluc @caseyedavis12 when this was brought up during a design meeting, I think we concluded that the facet cancelation controls would still be present (i.e. those little boxes that have the selected facet plus an "x" for canceling the facet). Is that the case?

**Comment by mccalluc** [comment]
@afred: So they are present in the bar at the top, pretty much like AAPB, but right now, once you select an option from a facet menu it it just disappears from the menu, and can only be deselected up top.
- One obvious way of deselecting seems like enough.
- We're tight on horizontal real estate: Does every menu option now also need a blank space were the X would go?
- This UI is diverging pretty far from BL, and it would need to be done from scratch.

I do agree this part of the UI does need more thought (#87), but that shouldn't block this PR.
