### ISSUE TITLE
Invalid xml in latest zip from Kevin

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#84]
@foo4thought : The ingest hasn't completed, so I can't give you the clean report, but out of 26K records I have 125 errors. Not bad. List-as-far-as-I've-gotten is attached. Some of them are schema errors. Others (empty content) are ad hoc checks that I've added. I could be wrong on those.

- [ingest-errors-1-21.txt](https://github.com/WGBH/openvault3/files/99943/ingest-errors-1-21.txt)

Thanks!

**Comment by foo4thought** [comment]
IDK the validation errors about "This element is not expected."  They appear in the proper order, have the correct name, namespace, etc.  Truly null elements will end in '/>' so the appearance of dual tags open/close "empty-looking" data is wrapping whitespace character(s).  I confirmed that in the FMP source.

**Comment by mccalluc** [comment]
Hmm, so our theory is that Nokogiri's interpretation of the XSD is buggy? Maybe, but this needs to stay open until the errors go away, one way or another.

**Comment by mccalluc** [comment]
@foo4thought : back in your court. Looking at one record:

```xml
<pbcoreDescriptionDocument xmlns="http://www.pbcore.org/PBCore/PBCoreNamespace.html" annotation="V_F98F1F90D7E84F77A06524CCDC26EC83">
  <pbcoreAssetType>Program master</pbcoreAssetType>
  <pbcoreAssetDate dateType="Item Date">07/20/1992</pbcoreAssetDate>
  <pbcoreIdentifier source="Open Vault UID">V_F98F1F90D7E84F77A06524CCDC26EC83</pbcoreIdentifier>
  <pbcoreTitle titleType="Program">BOB AND RAY : THE ONE AND ONLY</pbcoreTitle>
  <pbcoreAnnotation annotationType="Duration">00:56:00:00</pbcoreAnnotation>
  <pbcoreAnnotation annotationType="Media Type">Video</pbcoreAnnotation>
</pbcoreDescriptionDocument>
```

Error:
```
Schema validation errors: 
Element '{http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreAnnotation': 
This element is not expected. Expected is one of ( 
  {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreTitle, 
  {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreSubject, 
  {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreDescription 
)
```

and the schema:
```
...
<xsd:element maxOccurs="unbounded" minOccurs="1" name="pbcoreDescription"
...
```

Basically, the schema parse errors are based on a state machine, and so very often they are a long list of optional elements, and then the one required one that is missing, as in this case.

I think we were getting a small enough number of errors that maybe the fix is to just do the cataloging that needs to be done? That can be between you and Casey.

**Comment by mccalluc** [comment]
@foo4thought : There are still errors in the latest I have from you. I can give you a full list maybe later in the day, but for example:
>
WARN [2016-01-29 13:11:15]: /Users/chuck_mccallum/Downloads/2015_OV_MASTERS_FINAL_pbcoreRENAMED.zip :: V_184C15CF434948629BB6E255699B626F.xml : Schema validation errors: Element '{http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreGenre': This element is not expected. Expected is one of ( {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreTitle, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreSubject, {http://www.pbcore.org/PBCore/PBCoreNamespace.html}pbcoreDescription ).

Still missing description, I think?

**Comment by mccalluc** [comment]
[Warnings from the latest full ingest](https://github.com/WGBH/openvault3/files/110416/just-warnings.txt)

**Comment by Muraszko** [comment]
@mccalluc @foo4thought 
I have a ticket to myself to fix the 61 asset_type errors you are getting 
#46

**Comment by mccalluc** [comment]
Latest ingest has fewer error: I'm going to close this, and open new more granular bugs for the different kinds of errors.
