### ISSUE TITLE
Test facet OR queries

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#86]
I copied over a lot of complicated logic to support OR queries from AAPB. If this is something we definitely do not need, I'd like to remove it from the OV3 codebase, but it's not doing that much harm as-is, either. The worst scenario would be to remove it and then re-add it. @caseyedavis12?

**Comment by caseyedavis12** [comment]
@mccalluc: It would be good to have the option of conducting OR queries on Open Vault.

**Comment by mccalluc** [comment]
ok: Machinery is already in place: just want to add a test.

**Comment by mccalluc** [comment]
(This machinery is about ORing facets: it does not support OR in the plain text search.)
