### ISSUE TITLE
Better not to implement multi-column facet lists?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#87]
I don't want to jump in and just do the multi-column facets as in the spec.
- That's not the default, and as with anything else, we should ask whether the non-default is really worth the extra effort.
- Right now, multiple facets can be open simultaneously: If they were multiple column they would overlap, with the ones to the right on top, I think. That would be really ugly, so we'd probably want to allow only one at a time, or somehow bring the most recently open to the top. (More work, and disabling more-than-one-at-a-time might actually be the wrong direction.)
- Any multi column approach is not going to work in mobile with bootstrap: The problem is still there.
- If folks typically do a phrase search before narrowing by facet, there might not even be enough facet values that we would typically even need columns.

@caseyedavis12 : I want to diverge from the spec here, and would like your buy-in.

**Comment by caseyedavis12** [comment]
@mccalluc: Can I see what the single-column facet looks like on your machine?

**Comment by mccalluc** [comment]
Multi-column facets are done and work well enough. Closing this.
