### ISSUE TITLE
Scholar Exhibits

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#9]
On the homepage, a box appears below the rotating gallery that says "Scholar Exhibits." See: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553422/OpenVault_final%20comps_v3.jpg

When a user clicks on this button, it takes the user to the scholar exhibits index page. The scholar exhibits are ordered alphabetically by the last name of the curator: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553425/OpenVault_final%20comps_v33.jpg 

When a user clicks on one of the scholar exhibits, the user is taken to that scholar exhibit with the abstract tab as default: https://atlas.wgbh.org/confluence/pages/viewpage.action?spaceKey=OV&title=OV+Styled+Comps+V.3&preview=/26553443/26553435/OpenVault_final%20comps_v313.jpg

**Comment by mccalluc** [comment]
All of this is in place, except for the sorting: I'll make a new bug for that so it's not lost.
