### ISSUE TITLE
UI for play-from-point-in-transcript?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#99]
@caseyedavis12 : Specs did not spec how playback can be started from a given point in the transcript. I'm going to run with this:
<img width="314" alt="screen shot 2016-01-28 at 1 19 37 pm" src="https://cloud.githubusercontent.com/assets/730388/12654446/01f86c84-c5c2-11e5-862b-f93aa10dfa11.png">

(Where the little triangles get normal link mouse-over behavior, etc.)

If you think it's visually obtrusive we could hide it except on hover, or something like that.

Another possibility would be to make all the text respond to clicks, but I think that would likely be an annoyance and would get in the way of plain copy-and-pastes.

**Comment by caseyedavis12** [comment]
@mccalluc: I think this looks good.

**Comment by mccalluc** [comment]
Fix in #102
